### ISSUE TITLE
Train Dispenser NBT ignore

### ISSUE THREAD

**Issue by SmartGuy202** [Railcraft/Railcraft#1262] opened 2017-06-21 13:11 UTC
Using the DireWolf20 1.10 pack (MC 1.10.2). Trying to make a train dispenser setup and it will not launch a locomotive with a different whistle pitch. Each different locomotive has a separate whistle pitch when I place it down and I cannot get them to match with a tuner. I've had the issue before when trying to move said locomotives through my storage system, managed to get around that by setting it to ignore NBT. I may be doing something wrong and if I am please do explain it, but I think this feature could be useful never the less. Thanks.

P.S. I'm also getting that bug where the whistle plays vanilla sounds and not actually whistles. (sounds like a friggin Enderman infestation)

**Comment by liach** [comment] 2017-06-21 17:37
The P.S. part is duplicate of #1189. For that, I doubt it is caused by other mods in the modpack, as it never happened on Railcraft Patron Server.

The rest, however, may be an enhancement.

**Comment by CovertJaguar** [comment] 2017-06-22 07:13
Odd... I know when I wrote the thing it specifically ignored those bits.

**Comment by CovertJaguar** [comment] 2017-06-22 07:18
I suspect canBuildTrain() no longer ignores NBT due to changes to StackKey.

**Closed as completed** 2017-06-23 08:12 UTC
Labels: bug, low priority, carts
