### ISSUE TITLE
Steam turbine structure stops working properly after world reloading

### ISSUE THREAD

**Issue by ybogo** [Railcraft/Railcraft#1996] opened 2021-01-06 21:26 UTC
**Description of the Bug**
Texture of all blocks becomes same (as on pic)
![2021-01-06_13 25 37](https://user-images.githubusercontent.com/18507314/103821315-c9d19d80-5022-11eb-8b16-143bdf7f418a.png)
![2021-01-06_13 26 00](https://user-images.githubusercontent.com/18507314/103821317-cb02ca80-5022-11eb-9b47-8c3f5c48429b.png)

Turbine interface becomes unavailable (right click make nothing) but turbine still producing energy.
It can be fixed by crushing one block and placing it again.

**To Reproduce**
1. Create working steam turbine,
2. Exit to main menu,
3. Load world again

**Expected behavior**
Turbine structure should work properly after world reloading

**Logs & Environment**
Railcraft version 12.0.0
Forge version 14.23.5.2854

**Comment by TheFear101** [comment] 2021-01-15 14:21
I had the same issue. Fix was to make sure the entire structure was in the same chunk.

**Comment by gatoborrachon** [comment] 2021-12-17 03:55
>  Fix was to make sure the entire structure was in the same chunk.

I can confirm this works, many thanks, hope this was fixed in dev environment

**Comment by gatoborrachon** [comment] 2021-12-20 19:17
just want to add that, when i try to enter to the GUI of the Steam Boiler (when it is broken like the second pic of this issue) i present the same exact behavior that this issue describes: https://github.com/Railcraft/Railcraft/issues/1961

**Comment by CovertJaguar** [comment] 2022-06-01 04:07
Probably fixed by 12.1.0

**Closed as completed by CovertJaguar** 2022-06-01 04:07 UTC

**Comment by gatoborrachon** [comment] 2022-06-01 15:52
let me try it

**Comment by gatoborrachon** [comment] 2022-06-01 16:15
yeah, it seems to be fixed
