### ISSUE TITLE
Duplicating Carts

### ISSUE THREAD

**Issue by Suterusu1337** [Railcraft/Railcraft#974] opened 2016-10-28 16:31 UTC
I left a Steam Loco running by itself (no one logged in) for ~8hours.  I had attached to it: tank cart, iron chest cart, diamond chest cart, admin anchor cart.  The server did not reboot during this time.

After logging back in, I found the entire train missing, less the loco that had duplicated itself.

Upon breaking both Steam Locomotive, I had 2 exact copies, same name and all.

I check the entire rail system, all of the carts attached were gone.  No one else had logged in since to mess with any of the trains, so it wasn't a user issue.

http://i.imgur.com/HfPaPK6.jpg

Edit:
RC version 9.12.2.0
Forge: 10.13.4.1566

**Comment by Suterusu1337** [comment] 2016-10-28 23:51
New train ran into old loco-less train and it appeared.  Somehow the _entire_ train became duped.  (loco, carts, etc)  Even the contents of the chest carts were duped.

http://i.imgur.com/JVGZd9w.jpg

Later on, both loco detached from their respective trains and ran into each other head on until they ran out of water and shutdown.  As in, where the carts appeared were ~30 chunks away from where I found the loco.

**Comment by CovertJaguar** [comment] 2016-10-29 12:13
Duplicate of #585

**Closed as completed by CovertJaguar** 2016-10-29 12:13 UTC
Labels: duplicate
