### ISSUE TITLE
Force tracks may get broken after world re-open

### ISSUE THREAD

**Issue by Vodulm** [Railcraft/Railcraft#1977] opened 2020-10-21 18:36 UTC
https://vimeo.com/470350580

[latest.log](https://github.com/Railcraft/Railcraft/files/5418087/latest.log)

[debug.log](https://github.com/Railcraft/Railcraft/files/5418085/debug.log)

**Comment by Vodulm** [comment] 2020-10-21 18:49
Seems not happening if they have separate Feeder units...

**Comment by CovertJaguar** [comment] 2022-06-01 04:35
Duplicate of #1988

**Closed as completed by CovertJaguar** 2022-06-01 04:35 UTC
Labels: duplicate
