### ISSUE TITLE
Invisible metal post

### ISSUE THREAD

**Issue by kylesy20** [Railcraft/Railcraft#2025] opened 2021-09-07 11:23 UTC
Problem persists on the latest release of Railcraft on both 1.10,2 and 1.12.2

![2021-09-07_19 21 23](https://user-images.githubusercontent.com/23195822/132336687-f32fea42-e82a-4259-9a5f-d42f6e73271e.png)

**Comment by CovertJaguar** [comment] 2022-06-02 19:46
Duplicate of #1788

**Closed as completed by CovertJaguar** 2022-06-02 19:46 UTC
Labels: duplicate
