### ISSUE TITLE
Add configuration to disable specific cross-mod features, rather than entire mods

### ISSUE THREAD

**Issue by vishtheshnu** [Railcraft/Railcraft#1620] opened 2019-01-04 19:42 UTC
**Is your feature request related to a problem? Please describe.**
I'm developing an expert style modpack with Railcraft, with Forestry's Sturdy Casing having a more difficult recipe, and Railcraft's Crushed Obsidian being required for certain recipes. When I remove all recipes for the Sturdy Casing using crafttweaker and add my own, the new recipe for the Sturdy Casing added by railcraft (8 brass ingots surrounding an empty center in a 3x3 crafting table) isn't removed, which hurts the balance of the game. I can remove it by disabling the Forestry integration in the configs, but it removes other features that I would like to have. With Crushed Obsidian, I want to force players to craft the rock crusher, but railcraft also adds a recipe to make crushed obsidian with IC2's macerator, and I don't want to disable the entirety of IC2 integration, just the new macerator recipe.

**Describe the solution you'd like**
Increase the number of configuration options under cross-mod compat such that specific features for each mod (like added recipes or the ability to make a block in another machine) can be enabled or disabled.

**Describe alternatives you've considered**
Crafttweaker doesn't work when removing crafting recipes, and disabling the entirety of the mod compat in the config file removes too much functionality for just a single feature.

**Additional context**
No additional context. Thanks for taking the time to read this!

**Comment by Trinsdar** [comment] 2019-01-04 21:18
Might be related to #1610

**Comment by CovertJaguar** [comment] 2019-01-08 00:42
Duplicate of #1610. Same issue is that the recipe is being registered too late for CraftTweaker to see it.

**Closed as completed by CovertJaguar** 2019-01-08 00:42 UTC
Labels: duplicate
