### ISSUE TITLE
Conflicted recipe with Extreme Reactors

### ISSUE THREAD

**Issue by Sekra** [Railcraft/Railcraft#1235] opened 2017-06-01 03:04 UTC
I'm having an issue with Extreme Reactors conflicting with a Railcraft recipe;

Currently for Railcraft Creosote oil is created by cooking coal or charcoal in a normal furnace, unfortunately with Extreme Reactors this gets overridden as Graphite Bars.. Since the Railcraft method is just a temporary thing until multiblock devices are re-implemented, not sure how to handle this issue. But at least you know about it now.

**Comment by liach** [comment] 2017-06-01 05:50
Use alt recipes.

**Comment by Generalcamo** [comment] 2017-06-01 12:36
@Sekra This is due to the lack of the coke oven right now (as you mentioned). I can confirm it will be fixed totally in 10.3. I'm not sure if it is possible to fix it before then unfortunately.

**Comment by liach** [comment] 2017-06-01 13:32
@generalcamo alt recipes for tracks are using sticks.

**Comment by Sekra** [comment] 2017-06-01 16:48
Excellent news! I should have taken a better look at the configs.. It would seem that Extreme Reactors also have an option to change their recipes from smelting to crafting, if anyone else runs in this same issue. I've also updated my report to their github about the info you posted here.

**Comment by Twisted-Code** [comment] 2017-06-03 15:05
There is also Immersive Engineering's Coke Furnace for those who have or plan to have Immersive Engineering

**Comment by liach** [comment] 2017-06-06 16:54
I think this issue is not really meaningful. Hope you can get a recipe conflict fixer like crafttweaker for now.

**Closed as completed by liach** 2017-06-06 16:54 UTC
Labels: mod compatibility
