### ISSUE TITLE
Tunnel Bore Suggestion

### ISSUE THREAD

**Issue by Ashonee75** [Railcraft/Railcraft#1218] opened 2017-05-21 21:52 UTC
I'd like to suggest implementing a large bore cutting head.

Currently the tunnel bore does a 3x3 square tunnel.  I like to replace the walls with a more decorative block.  I'd love to see "large" bore heads that dig an additional block in each direction to make a 5x5 hole and leaves the corners. This way i can fill in the space with a decorative block with out having to dig out the walls.

Recipe suggestion would be an existing bore head surrounded by 8 of the component materials, ie 8 iron ingots surrounding an iron bore head, 8 steel ingots surrounding a steel bore head and 8 diamonds surrounding a diamond bore head (or 4 steel ingots on the corners and 4 diamonds on the sides if 8 diamonds seems excessive).

I would also suggest "large" bore heads double the durability if their smaller cousins, but since they would be digging out 21 blocks instead of 9 there would be an effective 14% shorter tile distance they could travel on one bore head.

The tunnel bore would be a block above the area it is cutting however it would be able to drop ballast to lay track on.

A further suggestion on the same line would be to allow the tunnel bore to place the walls itself, either via blocks the player supplies, or by adding the raw materials for concrete which the tunnel bore could convert into concrete walls.

**Comment by liach** [comment] 2017-05-21 22:51
However, tunnel bore will receive a major overhaul in code soon. We will see at that time.

**Comment by Generalcamo** [comment] 2017-05-22 00:11
Duplicate of #649

**Closed as completed by Generalcamo** 2017-05-22 00:11 UTC
Labels: duplicate, enhancement, question or discussion, carts

**Comment by liach** [comment] 2017-05-22 00:18
@Ashoneeplayswithballs Comment in that issue instead.
