### ISSUE TITLE
crash on minecraft version 1.10.2 on both 10.1.2 railcraft and 10.2.0

### ISSUE THREAD

**Issue by jayyyin** [Railcraft/Railcraft#1342] opened 2017-10-05 22:03 UTC
almost the identical error for both versions of railcraft

https://pastebin.com/k5V06wY0

**Comment by liach** [comment] 2017-10-06 00:55
1. This is caused by other mods that add items with incorrect capabilities. Remove half by half to test.
2. Will be fixed once version containing #1321 is released.

**Comment by liach** [comment] 2017-10-15 16:35
@jayyyin Any updates?

**Comment by jayyyin** [comment] 2017-10-16 20:38
@liach discovered it was a bug in forge 12.18.3.2488 for minecraft 1.10.2 caused a conflict between Tinker's construct and railcraft so, unrelated it wasn't directly related to railcraft

**Comment by liach** [comment] 2017-10-17 00:46
thanks!

**Closed as completed by liach** 2017-10-17 00:46 UTC
Labels: question or discussion, needs verification
