### ISSUE TITLE
Can't fill tankcart with fluid loader

### ISSUE THREAD

**Issue by Shandoo94** [Railcraft/Railcraft#1603] opened 2018-12-28 16:40 UTC
**Description of the Bug**
I am unable to fill a tankcart with a fluid loader. Rightclicking the cart with a waterbucket also does nothing. The Tankcart itsels also does not show a UI after rightclicking it with an empty hand.

**To Reproduce**
1. Place tank cart on a track 
2. Place Fluidloader directly above the cart
3. Fill Fluidloader with water (has to be through a tank or something similar, becouse the Loader also doesn't accept buckets)

**Expected behavior**
The tankcart fills with water

**Screenshots & Video**
![2018-12-28_17 35 37](https://user-images.githubusercontent.com/21018028/50521822-e0ee6400-0ac7-11e9-849f-1507372afc9e.png)
![2018-12-28_17 35 46](https://user-images.githubusercontent.com/21018028/50521823-e0ee6400-0ac7-11e9-811c-b2ba3a91739d.png)

**Environment**
Railcraft 12.0.0-beta2
forge 14.23.5.2796

**Comment by liach** [comment] 2018-12-28 16:43
duplicate of #1549

**Closed as completed** 2018-12-28 16:43 UTC
Labels: duplicate

**Comment by Shandoo94** [comment] 2018-12-28 16:55
I think there was an misunderstanding. My problem is not that I can't pump water into the Fluidloader, which is possible (See screenshot). But rather that ich can't pump fluids into the Tankcart at all.

![2018-12-28_17 54 28](https://user-images.githubusercontent.com/21018028/50522137-b0a7c500-0ac9-11e9-989e-92b0d95ef769.png)

**Comment by liach** [comment] 2018-12-28 17:00
Updated that issue to include the detail you want.
