### ISSUE TITLE
Fluid Cart fluid issues

### ISSUE THREAD

**Issue by Natesky9** [Railcraft/Railcraft#1270] opened 2017-07-11 05:55 UTC
testing on the creative server

- [x] fluid carts won't accept fluid from items
- [x] fluid doesn't update until gui is opened

- [ ] somehow, fluid can exist/filter can be changed on a tank cart with a different filter
![2017-07-11_01 23 20](https://user-images.githubusercontent.com/1789946/28052979-082341fe-65dc-11e7-88d0-11afcb006c30.png)

**Comment by liach** [comment] 2017-07-12 03:05
The update thing is duplicate of #1194, but other bugs are fresh.

**Comment by liach** [comment] 2017-07-16 20:58
All three bugs have been addressed in #1285.

**Closed as completed** 2017-07-18 03:02 UTC
Labels: bug, low priority, carts, inventory

**Comment by liach** [comment] 2017-07-18 05:37
For the fluid can exist part, it is intentional. However, after the filter is set, you can no longer input the old type of fluid into the cart.
