### ISSUE TITLE
Migrate to 1.11.2, 1.12.2, and 1.13

### ISSUE THREAD

**Issue by Generalcamo** [Railcraft/Railcraft#1232] opened 2017-05-31 03:09 UTC
### If you need help building/running, read https://github.com/Railcraft/Railcraft/wiki/Running-instructions-for-Minecraft-1.12.2 ~#1454~ instead!

This issue serves as a basic checklist for all the things that need to happen before a release is made for 1.11.

This issue is purely for tracking purposes only. No claims of priority, milestone, or any sort of release date is made here.

- [x] Migrate all `ItemStack` Null checks to `InvTools.isEmpty()` (Except in outside APIs)
- [x] Migrate all `null` `Itemstack`s to `InvTools.emptyStack()` (Except in outside APIs)
- [x] Replace `stack.stacksize--` with `InvTools` methods (That field got wrapped)
- [x] Use stable mapping for 1.10.2 which includes a lot of mapping changes for 1.11
- [x] Upgrade Buildcraft API to its 8th iteration (may require additional work, as this code hasn't been updated since 1.8)
- [x] Upgrade all other Mod APIs (IndustrialCraft 2, Forestry)
- [x] Use forge energy instead of outdated CoFH API (#1203) 
- [x] ~~Compile against 1.11 MCP (stable-32)~~ dropped in favor of 1.12.2
- [ ] Add ways to generate json files for dynamic recipes/loots (similar to dynamic textures?)

More edits by @liach:
- [x] Compile against 1.12.2 MCP (daily build) (easy once moved to 1.11)
- [x] Work on the new fluid ingredient
- [ ] Open forge pulls when needed
- [ ] Split up item/block ids if possible (no more id limit)

**Comment by CovertJaguar** [comment] 2017-05-31 03:11
The only part of the Buildcraft API is used extensively is the Trigger/Action API.

**Comment by liach** [comment] 2017-05-31 03:56
@CovertJaguar Priority?

**Comment by Generalcamo** [comment] 2017-05-31 04:01
No priority ATM. At all I mean.

**Comment by CovertJaguar** [comment] 2017-05-31 04:02
Priority equals "do what you can while working on other things".

**Comment by vico93** [comment] 2017-06-05 18:59
Is there any way we could help 1.11 dev? I'm not a Java coder, but i could test the nightly builds if you like.

**Comment by liach** [comment] 2017-06-05 19:19
@vpontin Go to https://patreon.com/CovertJaguar to support him and get beta builds on 1.11 once it's published.

**Comment by vico93** [comment] 2017-06-06 10:13
Dont have money for that. Sorry

**Comment by Generalcamo** [comment] 2017-06-06 13:42
Railcraft is currently not at a state of needing public Nightly builds. Test builds are given to the Patreons as private betas, and to the public as the public beta releases (latest being 10.1.2).

**Comment by liach** [comment] 2017-06-06 14:13
Only betas for version migration would be public on curseforge, I think. At least this is the case for 1.6 to 1.7 and 1.7 to 1.10

**Comment by CovertJaguar** [comment] 2017-06-06 17:27
Yes, generally after significant code change caused by an update, the final beta version will get posted publicly for testing purposes. But other than that, its not really necessary. I have plenty of testers between patreons and the server.

**Comment by liach** [comment] 2017-06-06 20:00
@Generalcamo We also need to replace the direct manipulation of stack sizes.

**Comment by liach** [comment] 2017-07-07 05:00
@jefflivsky

**Comment by liach** [comment] 2017-07-07 05:00
Misclick.

**Comment by Dockter** [comment] 2017-09-20 19:57
@liach where we at with the 1.12.1 update for Railcraft?  Been trying to ping you on IRC but your not around.

Thanks,

**Comment by P3rf3ctXZer0** [comment] 2017-09-29 20:19
Eagerly await 1.12.2 release - also can anyone commit to code? I have a few modders that might help.

**Comment by liach** [comment] 2017-09-30 06:39
it's going to take long. all code needs to be reviewed by @covertjaguar and he is going on to a trip in the wild.

**Comment by gri3229** [comment] 2017-10-24 18:36
@liach! So let the @CovertJaguar give permission to other coders to do it! Many are looking forward to this mod on the new versions.

**Comment by liach** [comment] 2017-10-24 23:53
Ehhm, he is on a hunting trip right now...

**Comment by VirtualGaming1** [comment] 2017-11-15 07:09
any update?

**Comment by liach** [comment] 2017-11-15 07:46
@VirtualGaming1 No progress in the recent month. Looking forward...

**Comment by P3rf3ctXZer0** [comment] 2017-11-26 16:41
By the time this gets ported we will be on 1.13 XD

**Comment by liach** [comment] 2017-11-26 16:59
we can just port it to 1.13 if people request a lot, i guess

**Comment by vico93** [comment] 2017-11-27 00:52
i wonder what would be the code changes to port to 1.13...

**Comment by Dockter** [comment] 2017-11-27 00:53
There are lots of under the hood changes coming in 1.13 that will make the update to 1.12 seem tiny.

**Comment by liach** [comment] 2017-11-27 01:11
@Dockter I don't really mind any more... 1.8's rendering and 1.11's item stacks are already crazy. I guess we can handle another huge change like 1.13 (many railcraft items are already non meta, I think?)

**Comment by CyanideCarrot** [comment] 2017-11-27 01:34
1.13 is basically the "Break everything pointlessly" update
Not just referring to mods being broken, but almost everything is going to be broken, and for no content to be added

**Comment by Dockter** [comment] 2017-11-27 22:33
@bballboy2002 nothing could be further from the truth.  Getting rid of the metadata and creating actual items and blocks out of all these damn sub items is long overdue.   Mojang had to do this in order to add new content.  So many of their block and item arrays were at their max.

**Comment by liach** [comment] 2017-11-27 22:40
@Dockter I suggest you talking to CovertJaguar on IRC and seeking to join #railcraft and #railcraft-dev channels on esper.net so that we can ask him to find things out more effectively.

Yes, 1.13 removed the upper limit on item and block ids! Yay! And sponge api suffers less from the reduction of meta data. There IS new content: Bark blocks!

**Comment by Dockter** [comment] 2017-11-27 23:00
There is more new content than just that but I won't be saying what until it goes public.  @liach is CJ back from hunting yet?

**Comment by liach** [comment] 2017-11-28 00:04
He is actually back.

> I need to get back to it, but always seems like something else is happening and distracting me

This is the biggest struggle he has currently, which I can hardly help.

**Comment by VirtualGaming1** [comment] 2017-12-11 03:04
can not wait for this mod to be updated to 1.12 for my modpack. but i might hold my modpack back a bit longer then from 1.10.2 to 1.12.2 (Was about a few month holding) reason is that most of the mods will be having a long re coding.

**Comment by BlackSmeim** [comment] 2017-12-20 13:22
And hows the progress?

**Comment by liach** [comment] 2017-12-20 15:22
@BlackSmeim Not much progress is made since CovertJaguar is not here. I suggest going on to https://discord.gg/Wr9zxmP and make a petition, because I want him to come out, too.

**Comment by border999** [comment] 2018-01-29 05:07
progress report?

**Comment by liach** [comment] 2018-01-29 05:57
@border999 https://github.com/Railcraft/Railcraft/tree/liach-1.10.2 contributions welcome

**Comment by Dockter** [comment] 2018-02-11 06:12
@CovertJaguar have you abandoned development work on RC?

**Comment by liach** [comment] 2018-02-11 06:19
Uhh, he comes out on railcraft discord as frequent as benimatic comes out on twilight forest discord now. He said he was busy with his life.

**Comment by liach** [comment] 2018-04-03 18:23
Update: first step pushed.
https://github.com/Railcraft/Railcraft/commit/b0fae9419e44ed9f58e5e69f8416038d61299732

Edit: also updated the main issue and checkboxes.

**Comment by vico93** [comment] 2018-04-04 13:32
@liach , did you have any CI set up for us download those beta builds? Just like [ComputerCraft](https://github.com/dan200/ComputerCraft) have (in https://cc.crzd.me)

**Comment by liach** [comment] 2018-04-04 13:56
@vpontin railcraft does not have ci builds. it is against the license.

**Comment by Dockter** [comment] 2018-04-04 13:58
Wait, what?  How is it against the license?

**Comment by liach** [comment] 2018-04-04 14:48
https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/LICENSE.md#distribution

> Except in the case of Public Mod Packs, you may not publicly distribute Railcraft on another site without CovertJaguar's explicit permission.

As defined, CI builds are illegal since CovertJaguar approved none. Moreover, the jar built with `./gradlew build` does not run. The best you can do is to run railcraft in development environment with `./gradlew runClient`.

**Comment by warplord** [comment] 2018-04-24 16:07
Any idea if we will see railcraft for 1.12? Definitely waiting for it to complete my full modlist I'd use.

**Comment by liach** [comment] 2018-04-24 16:22
The code is working for 1.12 but it depends on covertjaguar to release. He is the only one who can make a release.

**Comment by Njet75** [comment] 2018-05-01 09:42
Is Covertjaguar around?
Missing this mod dearly in 1.12.2

/Michael

**Comment by liach** [comment] 2018-05-03 22:31
@Njet75 Somehow I missed this comment. Sorry for the late response. CovertJaguar is not around, but I am trying my best and squeezing my free time to work on Railcraft. See https://github.com/Railcraft/Railcraft/tree/liach-1.12.2 if you know how to run mod from source code.

**Comment by shelbykauth** [comment] 2018-05-08 14:09
If CovertJaguar is really that busy with life, maybe it would be best if he handed the reins over to someone else.  Or rather, share the reins with someone else, like liach.  I mean, I understand that this mod is Jaguar's baby, but it's currently suffocating, and not for lack of development.  It would relieve pressure off of him and give the rest of us the mod we're so dearly missing.

Otherwise, this mod will soon become one we'll learn to live without, like Witchery 1.7.10, RedPower, ProjectRed, etc.  People are already making small mods to fill the void, including Extra Rails, Signals, and a few others.  And if we don't get it soon, Railcraft will be lost to the sands of time.

**Comment by warplord** [comment] 2018-05-08 14:17
I agree - CJ should absolutely let you liach make at least unofficial releases for 1.12, and when he comes around he can make a big real release - but now u are not getting the possible testing you could and we the players are missing a favorite mod ... Don't let Railcraft die please :(

**Comment by Twilix01** [comment] 2018-05-08 14:31
In reference to mods we learn to live with out, you should take another look at ProjectRed, it just released a 1.12 version yesterday! But getting back on topic for me though, I would like to see this mod not be stuck in development purgatory like Metallurgy 5 appears to be in.

**Comment by liach** [comment] 2018-05-08 14:42
Compared to project red, I certainly have more commit on railcraft than covers1624, the current maintainer of project red, on project red. https://github.com/MrTJP/ProjectRed/graphs/contributors

For your information, it seems CovertJaguar does not like me that much. A guy called Yopu became the first developer and left; ssotangkur came and left; Generalcamo came and left; I remained (probably by luck)

Another way to fix this may be us shouting "Hey CJ, we will make illegal distributions if you do not come back"; if he does care and appears again, it may be the best case.

For releasing, I do not think it is time yet. I am doing a refactor of recipes and api, which is the reason I merged two pull requests without pushing any code.

**Comment by warplord** [comment] 2018-05-08 14:46
Well all I meant was that all your hard work would be wasted if a railcraft is left to die in 1.10 forever. So when u come in a release-like state maybe you should consider making an unofficial release if nothing is heard from CJ. It certainly beats leaving the mod to die and all of your and the previous maintainers' work go to waste. Just my opinion. 

I am happy to see that you do work on Railcraft though - gives me hope we might one day see it back for 1.12.

**Comment by shelbykauth** [comment] 2018-05-08 15:09
Did It!?!?  Sweet!  Thank you for the info, Twilix01!  Though my point still stands that RedPower died and ProjectRed stepped up to replace it.  And we don't want that to happen to Railcraft.

As for the refactors, that makes sense.  That is a perfectly valid reason for not being available yet.  The main developer going off on a hunting trip and telling everyone else that they can't touch the mod is not a valid reason, not for something that's already met the public masses and has to update to stay in use.

I'm sorry he doesn't seem to like you liach.  That sucks.  I do understand his desire to maintain control over his baby when so many developers have came, touched, and left.  But still.

**Comment by Njet75** [comment] 2018-05-08 15:15
@liach Hang in there.We all love you :)

**Comment by warplord** [comment] 2018-05-08 15:24
We do and we have our hopes in you to eventually see RC again :) Keep up the good work!

**Comment by liach** [comment] 2018-05-08 16:28
:sweat:

**Comment by Spenny519** [comment] 2018-05-08 18:16
@liach i just tryed using the version of railcraft from this link https://github.com/Railcraft/Railcraft/tree/liach-1.12.2  and it didnt work
Help plz!!!

**Comment by Ommina** [comment] 2018-05-09 08:23
> The main developer going off on a hunting trip and telling everyone else that they can't touch the mod is not a valid reason...

This is not a forum, and I feel uncomfortable treating it as such, but I don't want to leave this unremarked.  CJ is not just the "main developer" -- he's the _owner_.  And that really does mean he can leave it as is, or delete the repository tomorrow and move on with his life.  The licensing is really quite clear.

I don't like it either, as I so desperately want to be running it in 1.12.  I do hope that @liach will not see his work go to waste.  But, however tempting it might be, we can't just kick the license to the curb.  Forget the legalities; it's disrespectful.

**Comment by shelbykauth** [comment] 2018-05-09 12:11
I... you're right @Ommina 
Parent says "Because you'll get hurt", valid reason.  Parent says "Because I said so", not a valid reason.  But kids still have to obey the parents, regardless of the validity of the reasons.

> This is not a forum.

Again, you are correct.  I'll try to make this my last tangental comment.

**Comment by liach** [comment] 2018-05-09 13:53
well, there are a few ways to bypass the license in fact. but whatever.

**Comment by warplord** [comment] 2018-05-09 13:55
I just hope when Railcraft is in a ready state for 1.12 people who are interested (like me) can get to play it. We'll see what happens.

**Comment by liach** [comment] 2018-05-09 14:39
I'll just close this issue for now since all the main stuff needed for 1.12 are done. Those unmarked entries are proved to be optional. 1.13 update will be tracked in different issues in the future.

**Closed as completed by liach** 2018-05-09 14:39 UTC
Labels: good first issue, high priority, work in progress, alpha
