### ISSUE TITLE
Cant find switch track 

### ISSUE THREAD

**Issue by JoshBlyth** [Railcraft/Railcraft#1470] opened 2018-07-21 11:37 UTC
in latest update of 1.10.2 i cannot find any way to get the switch track from the creative menu or NEI

**Comment by LuigiHutch** [comment] 2018-07-21 11:42
Duplicate of https://github.com/Railcraft/Railcraft/issues/1364,  You get them by right-clicking tracks with a spike maul.

**Comment by JoshBlyth** [comment] 2018-07-21 11:43
thank you soooo much

**Closed as completed** 2018-07-21 14:18 UTC
Labels: not a bug, invalid, tracks
