### ISSUE TITLE
Dupe bug tinkers

### ISSUE THREAD

**Issue by DnTheMn** [Railcraft/Railcraft#967] opened 2016-10-26 10:48 UTC
im forwarding this here as that is what others have been instructed to do im unsure if they have or haven't but if they have just close this issue and additional information you need please let me know ill get back asap Dan.
https://github.com/BluSunrize/ImmersiveEngineering/issues/1586
https://github.com/whatthedrunk/allthemods/issues/241

**Comment by CovertJaguar** [comment] 2016-10-26 10:58
Duplicate of #934

**Closed as completed by CovertJaguar** 2016-10-26 10:58 UTC
Labels: duplicate
