### ISSUE TITLE
[1.10.2] Carts sometimes forget links

### ISSUE THREAD

**Issue by CovertJaguar** [Railcraft/Railcraft#882] opened 2016-09-02 18:35 UTC
No idea why, but I'm consistently getting some carts that forget they are linked after a game restart.

**Comment by liach** [comment] 2016-09-02 19:50
How?

**Comment by CovertJaguar** [comment] 2016-09-03 02:33
Links should be stored in the persistent entity NBT data and point at the other entities persistent UUID.

This is all handled in LinkageManager.java.

**Comment by liach** [comment] 2016-09-03 06:45
I mean how to reproduce it. Does it happen when you leave the chunk it's in?

**Comment by CovertJaguar** [comment] 2016-09-03 07:40
Restart game, wasn't enough to reload world.

**Comment by liach** [comment] 2016-09-10 04:54
Could you state the steps to reproduce it more clearly?

**Comment by CovertJaguar** [comment] 2016-09-10 07:44
Link a bunch of carts, quit the game, start the game, load world, see broken links. That's really all there is to it.

**Comment by liach** [comment] 2016-09-28 19:17
Can this still be reproduced?

**Comment by TheMrCaveman** [comment] 2016-10-08 06:39
This is still the case with beta 2!!!! It forgets ALL links when chunk unloads

**Comment by liach** [comment] 2016-10-08 15:38
Then it looks like a bug of storage of Railcraft NBT tags.

**Comment by Ristellise** [comment] 2016-10-09 00:51
huh maybe the game does not fully save all when quite save is pressed???

**Comment by AEnterprise** [comment] 2016-10-09 10:48
are all the entities properly registered in the registries? if not that could cause nbt to not get saved

**Comment by liach** [comment] 2016-10-11 01:52
In my opinion, this is probably an issue regarding NBT loading because the cart linking state always saves when a link is created or broken.

**Comment by liach** [comment] 2016-10-11 04:02
For me, I cannot reproduce it. I linked a bunch of carts, walked away, and went back. I saw those carts still linked. Quitting the game does not work either.

**Comment by Ristellise** [comment] 2016-12-19 04:30
@liach probably when chunks unload? you may need to walk away far enough.

**Comment by liach** [comment] 2016-12-19 04:43
Like 10000 blocks? Or just 1000 block? I tried to go 700 blocks away and return, and the carts remain linked.

**Comment by Ristellise** [comment] 2016-12-19 05:47
think like 10000 blocks...

**Comment by liach** [comment] 2016-12-19 06:02
Will try later. Thanks for your info.

**Comment by xbjfk** [comment] 2016-12-22 20:17
confirmed

**Comment by liach** [comment] 2017-01-03 19:11
Does this happen with certain types of minecart or all?

**Comment by liach** [comment] 2017-01-07 20:37
May this be a dupe of #585?

**Comment by Ruuubi** [comment] 2017-01-31 19:41
Experienced the same problem in the current version (10.0.1):
https://www.youtube.com/watch?v=NRi82tY2J1A

- Spawn carts and link them
- Exit world
- Reload world
-> Carts unlinked

I tried to reproduce it in a new world. Sometimes it did work as expected, other times it did not.
Tested it at world spawn and 10,000 blocks away. Doesn't matter if I logged out right besides the train or far away. The result was the same. (Tested in singleplayer, no idea about multiplayer).

**Comment by liach** [comment] 2017-02-02 03:03
@Ruuubi Cannot reproduce it, but I can see some weird behavior in cart physics.
![2017-02-01_18 59 42](https://cloud.githubusercontent.com/assets/7806504/22535631/25ac89ae-e8b1-11e6-9612-00c0a307204d.png)

**Comment by liach** [comment] 2017-03-03 21:04
Have we come up with a solution?

**Comment by CovertJaguar** [comment] 2017-03-03 21:36
Haven't looked at it recently.

**Comment by liach** [comment] 2017-04-20 07:50
Might this relate to the loading of nbt data instead of the stroage of it?

**Comment by liach** [comment] 2017-04-26 04:21
This issue has been observed several times on the official Railcraft server.

**Comment by liach** [comment] 2017-04-26 06:53
Side note: https://github.com/CovertJaguar/Railcraft/commit/f51e32dac5ec5e6140bc2e3b6dbb28a75de149f3

**Comment by liach** [comment] 2017-05-04 03:31
@CovertJaguar Can I mark this as `can't fix`?

**Comment by CovertJaguar** [comment] 2017-05-04 09:59
No, I have a possible fix in the wild being testing right this moment.

**Comment by liach** [comment] 2017-05-14 15:06
https://minecraft.curseforge.com/projects/world-utils#title-7
We should try with this mod.

**Comment by liach** [comment] 2017-06-07 00:42
@CovertJaguar This issue still exists, confirmed on the patron server.

**Comment by CovertJaguar** [comment] 2017-06-07 06:43
The Shunting Aura should provide the info necessary to fix it.

**Comment by liach** [comment] 2017-06-07 06:45
Can we try with dormant chunk cache disabled?

**Comment by CovertJaguar** [comment] 2017-06-07 06:57
Identify the problem first, then start looking for solutions.

**Comment by liach** [comment] 2017-07-16 08:01
Closing since we haven't reproduced this in a long time (especially on patron server) and some fixes were already pushed.

**Closed as completed by liach** 2017-07-16 08:01 UTC
Labels: bug, high priority, carts
