### ISSUE TITLE
Standard world spike cart crashes game

### ISSUE THREAD

**Issue by Nobody931** [Railcraft/Railcraft#1677] opened 2019-01-25 08:07 UTC
**Description of the Bug**
After putting an ender pearl into the standard worldspike cart, the game crashes my world and in a test world. Beta-4, Singleplayer world.
Important to note here is that the game did only crash, when I had at least one chunk loaded with the FTB Utilities "claimed chunks" interface. Crashes even after unloading the claimed chunks

**To Reproduce**
Load a world, where you use FTB Utilities chunk loading, with at least one chunk permanently loaded
1. Place standard worldspike cart on track
2. Open inventory of cart and put one ender pearl in
3. See the game crashing

**Expected behavior**
Standard world spike cart should not crash the game and accept the fuel.

**Logs & Environment**
CrashReport: https://pastebin.com/Cfqpt69Z
latest.log: https://gist.github.com/Nobody931/e8dc447bf8859d36da901c2ac9d37069

**Comment by liach** [comment] 2019-01-25 09:46
it's a duplicate of another worldspike crash on getting fuel initially.

**Closed as completed** 2019-01-25 09:46 UTC
Labels: duplicate
