### ISSUE TITLE
Crash when viewing coke oven recipes with coal coke item disabled

### ISSUE THREAD

**Issue by TheDeviantCrafter** [Railcraft/Railcraft#1640] opened 2019-01-11 11:41 UTC
**Description of the Bug**
When viewing the coke oven recipes in JEI, the game crashes. I've encountered this when checking the uses for coal and when clicking the arrow in the coke oven GUI.

I disabled coal coke in the config, which is almost certainly related. 

**To Reproduce**

1. In the `items.cfg file`, change `B:fuel_coke=true` to `B:fuel_coke=false`

**Expected behavior**
Viewing the recipe will not crash.

**Logs & Environment**
 - Full log: https://gist.github.com/TheDeviantCrafter/a7c5886309330f4d39e1a03e9017f429

 - Crash report (If available):  https://pastebin.com/AUfBkJUs

**Comment by liach** [comment] 2019-01-12 01:47
hmm, cj has refactored this and i wonder if this will still happen.

**Comment by CovertJaguar** [comment] 2019-01-12 03:10
Duplicate of #1628

**Closed as completed by CovertJaguar** 2019-01-12 03:10 UTC
Labels: duplicate
