### ISSUE TITLE
 it won't let me put the TBM

### ISSUE THREAD

**Issue by Palomero33** [Railcraft/Railcraft#2021] opened 2021-07-28 20:49 UTC
sorry for the translator.
When I try to put the TBM on the tracks it won't let me, I put it on it disappears, then the item appears on the ground and every time I try it it doesn't work, I hope you will help me because I need the TBM urgently please.

**Comment by maleksware** [comment] 2021-07-31 17:29
Possible duplicate of #2010, check it for now.

**Comment by maleksware** [comment] 2021-09-11 06:58
This bug was fixed in #2024.

**Closed as completed** 2022-06-01 01:01 UTC
