### ISSUE TITLE
Possible Resource Leak: Iron Tanks

### ISSUE THREAD

**Issue by pyure** [Railcraft/Railcraft#1823] opened 2019-04-24 02:06 UTC
**Description of the Bug**
Iron and Steel tanks may be leaking memory instead of liquids.

**To Reproduce**
Use an infinite fluid generator from whichever mod.
Pipe fluid into tank.  Wait 90-180 minutes.  Lag spikes will ensue.

**Negative Test**
Replace the RC tanks with tanks from another mod.  No lag.

**Expected behavior**
No lag

**Additional context**
* railcraft-12.0.0.jar
* forge-14.23.5.2835
* infitech 3 modpack (infitechs gotta have RC by tradition. duh.)
* We spent several days trying to narrow down and isolate this to a specific mod before wasting anyone's time; that said, our evidence is only empirical.  The common factor we've observed is Railcraft multiblock tanks, but it could also be that the various mods we've used for piping (Thermal Dynamics, Gregtech CE) are having difficulties working with the tanks for reasons specific to those mods.

**Comment by liach** [comment] 2019-04-24 02:18
@pyure Run on a dedicated server environment and get a garbage collector or java core dump. Your suspicion here is not enough without a dump like that in https://github.com/pyure/infitech-prototype/issues/447#issuecomment-480518724

**Comment by pyure** [comment] 2019-04-24 02:20
Understood, will do as advised.

**Comment by liach** [comment] 2019-04-24 02:21
You can do it both on a client and a dedicated server so that the developers can better spot the cause (i.e. whether this is host logic or render related)

**Comment by TLaviron** [comment] 2019-04-27 09:34
I've recreated the issue with a minimal example, using a railcraft iron tank and a water generator (from nuclear craft in this example, but it should be swappable with any other generator).

You can download the GC heap dump I've collected here : (https://drive.google.com/open?id=1NEKjUJH7c4AAUnZleYjagCXDfc6UhJLx)
Both client and dedicated server dumps are included.

As an important note, when I disabled foamfix with this setup, I did not encounter the memory issue.
It only seems to happen with both foamfix (version 0.10.5-1.12.2) and the RC iron tank.

**Comment by pyure** [comment] 2019-05-03 14:19
liach, in your opinion is this something more properly suited to annoying asie about?  If its a combination of the two mods causing the issue, it could just as easily be the other mod.

**Comment by pyure** [comment] 2019-05-08 22:55
Archengius from GT-CE made these comments, I'm tracking them here:

> @liach i'm 99% sure that RC tanks + foamfix memory leak is caused by RC's mods.railcraft.client.render.models.resource.FluidModelRenderer
> baking model newly created fluid model each frame, manually creating extended block state for it, baking quads with it
> it has chances to have huge issues with optimizations foamfix performs
> and in fact memory footprint is going to grow each draw frame
> proportionally to amount of frames per tick
> that also explains why @Georggi memory-leaked much faster than me with his 200+ FPS and mine limited to 60
> my suggestions are:
> a) cache baked models and their blockstates instead of creating them each frame
> b) switch fluid renderer implementation to simple manual rendering of 6 quads - that would also resolve issues with ugly scaling of fluid texture in tanks

**Comment by pyure** [comment] 2019-05-21 03:10
liach have you put any thought into this?  Its the number one negative issue with our users by far right now :( :(

**Comment by liach** [comment] 2019-05-21 03:14
Given cj is away now, I think the best bet is to write a coremod that fixes this issue. Let me take some time out for this

**Comment by pyure** [comment] 2019-05-21 20:15
Understood, won't pester you further.  Thanks kindly sir.

**Comment by CovertJaguar** [comment] 2022-06-16 02:25
Duplicate of #2015

**Closed as completed by CovertJaguar** 2022-06-16 02:25 UTC
Labels: bug, high priority
