### ISSUE TITLE
Locomotive bug

### ISSUE THREAD

**Issue by ccgfok** [Railcraft/Railcraft#1030] opened 2016-11-30 17:14 UTC
This happened when created link between locomotive (in this case, steam) and the cart. When start running, it was broken. 
Gif: https://gfycat.com/SaltyScentedAfricangroundhornbill

**Comment by Forecaster** [comment] 2016-12-01 08:04
Can you reproduce that in a new world and/or with just railcraft?

**Comment by ccgfok** [comment] 2016-12-01 10:10
It produces for both new world and new cart.
To re-produce:
1. Give your own steam and minecart.
2. Make a link between cart and steam loco. 
3. Add fuel + water, start running slowly.
4. After start running for a while, Its lost their link.
(Apply for electric and perpetuum.)
**Update**: Its happened when using train dispenser to make a train.
To reproduce:
1. Give your own locomotive, train dispenser, and some cart.
2.  Place train dispenser, create a pattern for train and put cart here.
3.  Use redstone to active, then create link for loco and 1st cart.
4.  Start run, and its lost link.

**Comment by ccgfok** [comment] 2016-12-01 17:05
Update: Its happened when using train dispenser to make a train.
To reproduce:
1. Give your own locomotive, train dispenser, and some cart.
2. Place train dispenser, create a pattern for train and put cart here.
3. Use redstone to active, then create link for loco and 1st cart.
4. Start run, and its lost link.
P/s: Its won't happen when using crowbar or coupler track kit to make a link.

**Comment by liach** [comment] 2017-03-13 23:44
I tested and cannot reproduce this. Did you get this result on a fairly laggy computer @ccgfok? As I see from the gif, your first link failed, probably because of lag.

**Comment by CovertJaguar** [comment] 2017-03-14 00:11
I think I've actually seen this in my own testing. I forget if I fixed it or not. Seems like I might have.

**Comment by ccgfok** [comment] 2017-03-22 12:54
@liach This was happen **if** the dynamic light for locomotive was activated **and** use the recomended Forge version (12.18.2.2107+). The latest Forge vesion (1.10.2-12.18.3.2254) disabled the dynamic light.
And yeah, my computer was only 2GB RAM, and the gif link I was tried to re-produce this bug.

**Comment by liach** [comment] 2017-05-14 14:59
Going back to #882... I think it might be caused by the storage in the map of cart links, or something similar.

**Comment by liach** [comment] 2017-05-17 05:32
We can only close this because this is a very rare single case and no one else reported this.

**Closed as completed** 2017-05-17 05:34 UTC
Labels: bug, low priority, can't reproduce, carts
