### ISSUE TITLE
Incompatible with touhoulittlemaid mod.

### ISSUE THREAD

**Issue by fengeraien** [Railcraft/Railcraft#1912] opened 2020-01-07 07:41 UTC
**Description of the Bug**
Incompatible with touhoulittlemaid mod.
mod version:1.1.8-beta-hotfix2
mod source:https://github.com/TartaricAcid/TouhouLittleMaid

**To Reproduce**
1.This cause a Server crash when server is starting. 
Server version:Catserver 1.12.2
server source:https://github.com/Luohuayu/CatServer
2.If i unistall RC12.0.0 or LittleMaid mod,server can start normally.

**Expected behavior**
I hope the issue can be solved.

**Screenshots & Video**
none.

**Logs & Environment**

 - Full log: 
https://gist.github.com/fengeraien/b74fc4451e1e619b23a38ac7242deee3

 - Crash report (If available): 
https://gist.github.com/fengeraien/3522bc1d1f0468f2fb9484a160f38106

**Additional context**
none.

**Comment by SeraphJACK** [comment] 2020-02-27 03:18
**Can't reproduce on a regular forge server!**

According to the crash-report, Touhou Little Maid's ItemSpellCard tried to load a client-side class during loading. But let's see the code:

https://github.com/TartaricAcid/TouhouLittleMaid/blob/master/src/main/java/com/github/tartaricacid/touhoulittlemaid/item/ItemSpellCard.java#L100

```java
Set<String> ids = FMLCommonHandler.instance().getSide().isClient() ? ClientProxy.CUSTOM_SPELL_CARD_MAP_CLIENT.keySet() : CommonProxy.CUSTOM_SPELL_CARD_MAP_SERVER.keySet();
```

I think it's CatServer that did something wrong, but not RailCraft or TouhouLittleMaid. You should probably ask the developer of CatServer and close this issue.

**Comment by SeraphJACK** [comment] 2020-02-27 03:36
You can try updating touhou little maid version to [1.1.9-release](https://www.curseforge.com/minecraft/mc-mods/touhou-little-maid/files/2858200), probably solves your problem. Whatever, this is **not** a Railcraft issue, you should close this. (See TartaricAcid/TouhouLittleMaid#165)

**Comment by liach** [comment] 2020-02-27 03:39
Thanks @SeraphJACK :heart:

**Closed as completed by liach** 2020-02-27 03:39 UTC
