### ISSUE TITLE
crash when trying to place tank cart

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#1795] opened 2019-03-22 13:56 UTC
**Description of the Bug**
Tried placing a tank cart on a rail and crashed, there was a chest cart close but can't tell if that would be related at all.

**Logs & Environment**
https://hastebin.com/exujulixev.cs

**Additional context**
So far tank carts didn't cause any problems for me but I am not sure if I used them in Railcraft 12.0.0 - MC 1.12.2 yet.

Edit: World now crashes on load, will try to reproduce it in another world.
Edit2: Disabled tank cart in the config but the world still crashed after 2 seconds of moving around.

**Comment by WarlordWossman** [comment] 2019-03-22 14:19
So I tried placing a tank cart in a rather clean instance (only a few mods present) and I don't get a crash.

**Comment by liach** [comment] 2019-03-22 14:20
Can you put the log on github gist instead?

**Comment by WarlordWossman** [comment] 2019-03-22 14:23
https://gist.github.com/WarlordWossman/e224bb0b24b096b7b71709573205b3c5

**Comment by liach** [comment] 2019-03-22 14:30
Turns out to be a duplicate of turbodiesel4598/NuclearCraft#477

**Closed as completed by liach** 2019-03-22 14:30 UTC
Labels: not railcraft, mod compatibility
