### ISSUE TITLE
missing textures for many blocks

### ISSUE THREAD

**Issue by 0Navis0** [Railcraft/Railcraft#979] opened 2016-10-30 22:16 UTC
I don't know if it's normal, but many blocks and items have a missing textures. I suspect Optifine to be linked to this bug. 
![2016-10-30_23 02 50](https://cloud.githubusercontent.com/assets/17103411/19840459/8cb1c394-9ef6-11e6-8536-97fdc3e04ee7.png)
![2016-10-30_23 02 54](https://cloud.githubusercontent.com/assets/17103411/19840460/8e377a1a-9ef6-11e6-93c1-4a3ef36d1786.png)

**Comment by KnightMiner** [comment] 2016-10-31 02:11
Does it happen without Optifine? Obvious question if you suspect Optifine

**Comment by 0Navis0** [comment] 2016-10-31 02:38
Yeah it's Optifine which causes the problem.

**Comment by CovertJaguar** [comment] 2016-10-31 14:40
Duplicate of #924

**Closed as completed by CovertJaguar** 2016-10-31 14:40 UTC
Labels: duplicate
