### ISSUE TITLE
Minecart bug

### ISSUE THREAD

**Issue by Pavelsvt** [Railcraft/Railcraft#1982] opened 2020-11-04 15:39 UTC
**Description of the Bug**
When I use the Railcraft mod (1.12.2), all minecarts (both vanilla and those that were added by the mod) are bugged, semi-transparent (I can see the rails through them), and cannot be pushed by hand (though they still go downhill rather well).

**To Reproduce**

1. Install railcraft (I also use the immersive railroading, maybe it glitches the mod?)
2. Place block/cart on any rails.
3. See the rails through the ghosts of minecarts.

**Expected behavior**
I expected at least the vanilla carts to work as if the mod was not installed. This happens only when I uninstall the railcraft.

The game doesnt crash, but it looks weird and I also cannot push the carts, which makes them useless.

**Comment by Trinsdar** [comment] 2020-11-04 15:42
Semi transparency is not a bug, that's a holloween feature

**Comment by Pavelsvt** [comment] 2020-11-04 15:52
Really? Is there any way to turn it off? It looks weird. And do you have any idea why I cannot push those carts?

**Comment by Trinsdar** [comment] 2020-11-04 16:02
https://github.com/Railcraft/Railcraft/issues/1980#issuecomment-716066778
As for pushing a cart, i always assumed that it was intended you use a crowbar to push a cart.

**Comment by Pavelsvt** [comment] 2020-11-04 16:21
So its not a bug, thank you. But still, is there any way to turn off the semi transparency?

**Comment by Mega2223** [comment] 2020-11-04 18:01
If im not wrong you can turn it off in the Main Menu > Mods> RailCraft > Configs

**Comment by Ommina** [comment] 2020-11-04 20:00
It will also turn itself off on the 11th.

**Comment by Minecraft2p0** [comment] 2020-11-08 11:57
Thanks for the tip.

Do you have another one for a safe train tutorial? I can't handle it. The power converter and the steam boiler are particularly troubling for me. So so far I only use the steam engine

**Comment by Joker58th** [comment] 2020-11-09 15:22
I also came looking for a fix for this.  I use a shader and the carts look horrible.  Removed the shader and they are transparent which led me to this [issue](https://github.com/Railcraft/Railcraft/issues/1344).  I turned it off via the specified config and all looks correct now.

![image](https://user-images.githubusercontent.com/32574965/98560156-75ee4680-2275-11eb-97bb-403cfa3050b5.png)

**Closed as completed** 2022-06-01 04:15 UTC
Labels: working as intended
