### ISSUE TITLE
[1.10.2] Tunnel Bore doesnt drop into Chestcarts?!

### ISSUE THREAD

**Issue by Marcel40625** [Railcraft/Railcraft#1385] opened 2018-03-21 23:06 UTC
Hey there, tried today the Tunnel Bore and it seems not dropping his items into linked Chestcarts

any idea?

Running: Railcraft 10.3.1 - MC 1.10.2

Edit: Pulling out of Chestcarts seems to work (Tracks and Coal) bot not dropping.

**Comment by liach** [comment] 2018-03-29 17:56
Sorry for the late response, but I believe this is a duplicate issue. Duplicate of #1335.

**Closed as completed by liach** 2018-03-29 17:56 UTC
Labels: duplicate

**Comment by Marcel40625** [comment] 2018-04-03 08:07
ohh okay ... any idea how close to the next update you guys are? (dont want to push, only interested)

**Comment by liach** [comment] 2018-04-03 13:55
one month or more, but you can fix it via config.
