### ISSUE TITLE
Forestry API error

### ISSUE THREAD

**Issue by C0rn3j** [Railcraft/Railcraft#981] opened 2016-10-31 23:45 UTC
Relevant bit of the log: http://pastebin.com/vH36gXVf

Modlist: http://pastebin.com/KQYzk5xn

Forge 2116.

**Comment by CovertJaguar** [comment] 2016-11-01 02:43
Hmm...not sure why Gradle didn't pull in the latest version, I'm a couple days behind it looks like. Not a huge deal I guess, just no backpacks.

**Comment by CovertJaguar** [comment] 2016-11-01 02:46
Could you post the API loading section of the log as well...the part that says which jars the APIs are loaded from. I updated to 308, but don't see any errors on my end, I suspect an outdated API in some other mod.

Pokes @mezz

**Comment by mezz** [comment] 2016-11-01 04:25
It would be helpful to see the whole client log.
https://gist.github.com has no limit on the length of text posted there.
Ideally nothing should be including the Forestry API in their jar besides Forestry.

**Comment by C0rn3j** [comment] 2016-11-01 08:50
This ain't a client problem.

http://pastebin.com/SEipNVtR

Also unrelated issue - 

[08:41:41] [main/ERROR] [LaunchWrapper]: A critical problem occurred registering the ASM transformer class 

This has been in my startup log for a while now, any idea what it could possibly be causing it? I have no idea where to report it.

**Comment by CovertJaguar** [comment] 2016-11-01 11:06
I don't know what you did....but delete everything and start over...your install is all kinds of fucked up and the server you are connecting to has a hundred more mods than you have installed.

**Comment by C0rn3j** [comment] 2016-11-01 11:08
I am not connecting to any server! This is a server startup log! Not client!

**Comment by C0rn3j** [comment] 2016-11-01 11:24
I've deleted the config folder to avoid this being a config issue from an older mod but it changed nothing.

Moreover if you look at the logs you can see that forestry is complaining a lot too.

[11:21:04] [Server thread/WARN] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:charge_feeder:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.

**Comment by CovertJaguar** [comment] 2016-11-01 11:36
Well you definitely have client only mods installed.

I need the FML log, not whatever that is.

**Comment by C0rn3j** [comment] 2016-11-01 11:42
> whatever that is.

That's a server startup log >.<

> Well you definitely have client only mods installed.

Yup. 

> FML log

https://gist.github.com/C0rn3j/81a221453f4be90d47844a1138cd2db2/raw/9b7f0a0986aed8244275ac405e44b4961c7887bf/gistfile1.txt

**Comment by CovertJaguar** [comment] 2016-11-01 12:31
Try removing your core mods and client mods.

**Comment by JonnyBrando** [comment] 2016-11-07 17:50
## CLIENT SIDE ONLY (so far -- will port to private server later)

I've got the same issue.

The only thing loading the forestry API appears to be forestry itself.

https://gist.githubusercontent.com/anonymous/8ef2e7862359351f68b4f26e36684d70/raw/b0e4dbda1d666642ed8f4b3ea49b68a5eb545c40/fml-client-latest.log

I'll try updating forestry from 314 to 320 to see if that fixes it.

**Comment by JonnyBrando** [comment] 2016-11-07 18:05
Nope, same error after updating forestry. Any possiblity that @mezz changed the name of the tag for backpacks, or broke it some how with one of the newer updates?

```
[13:02:52] [Client thread/ERROR] [railcraft/railcraft]: Forestry API error, please update your mods. Error: java.lang.IllegalArgumentException: RailcraftConfig: item tag not found: backpack.trackman.t1
[13:02:52] [Client thread/ERROR] [railcraft/railcraft]: java.lang.IllegalArgumentException: RailcraftConfig: item tag not found: backpack.trackman.t1
[13:02:52] [Client thread/ERROR] [railcraft/railcraft]: mods.railcraft.common.core.RailcraftConfig.isItemEnabled(RailcraftConfig.java:888)
[13:02:52] [Client thread/ERROR] [railcraft/railcraft]: mods.railcraft.common.plugins.forestry.ForestryPlugin$ForestryPluginInstalled.registerBackpacks(ForestryPlugin.java:124)
[13:02:52] [Client thread/ERROR] [railcraft/railcraft]: Forestry API error: BackpackManager is loaded from jar:file:/C:/Users/jbruneau/AppData/Roaming/.minecraft/profiles/1.10/mods/forestry_1.10.2-5.2.16.320.jar!/forestry/api/storage/BackpackManager.class
```

New log below:
https://gist.githubusercontent.com/JonnyBrando/1a950a9457eb6c36c4cdd6513a39a266/raw/a4f1edbca625092f388938d67f7f1f79912c0d28/fml-client-latest.log

**Comment by bookerthegeek** [comment] 2017-02-26 05:04
Same issue, Here are the latest Logs:

First Error
```
[20:27:18] [Client thread/ERROR] [railcraft]: Forestry API error, please update your mods. Error: java.lang.IllegalArgumentException: RailcraftConfig: item tag not found: backpack.trackman.t1
[20:27:18] [Client thread/ERROR] [railcraft]: java.lang.IllegalArgumentException: RailcraftConfig: item tag not found: backpack.trackman.t1
[20:27:18] [Client thread/ERROR] [railcraft]: mods.railcraft.common.core.RailcraftConfig.isItemEnabled(RailcraftConfig.java:904)
[20:27:18] [Client thread/ERROR] [railcraft]: mods.railcraft.common.plugins.forestry.ForestryPlugin$ForestryPluginInstalled.registerBackpacks(ForestryPlugin.java:124)
[20:27:18] [Client thread/ERROR] [railcraft]: Forestry API error: BackpackManager is loaded from jar:file:/C:/Games/MultiMC/instances/AM/minecraft/mods/forestry_1.10.2-5.2.17.368.jar!/forestry/api/storage/BackpackManager.class
```

Second Error
```
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:charge_feeder:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:charge_trap:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:frame:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:wire:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:anvil:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:brick_abyssal:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:brick_bleachedbone:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:brick_bloodstained:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:brick_frostbound:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:brick_infernal:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:brick_quarried:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:brick_sandy:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:brick_nether:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
[20:28:00] [Client thread/ERROR] [forestry]: Received an invalid 'add-backpack-items' request 'builder@railcraft:glass:*' from mod 'railcraft'. Please contact the author and report this issue. For non-existent backpack builder.
```

Versions
```
  forestry_1.10.2-5.2.17.368
  Railcraft_1.10.2-10.0.1
```


Hope this helps

**Comment by bookerthegeek** [comment] 2017-02-26 05:52
Also, forgot to add
```
	List of loaded APIs: 
		* ForestryAPI|apiculture (5.0.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|arboriculture (4.2.1) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|circuits (3.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|climate (2.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|core (5.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|farming (2.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|food (1.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|fuels (3.0.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|genetics (4.7.1) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|greenhouse (5.2.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|hives (4.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|lepidopterology (1.3.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|mail (3.1.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|multiblock (3.0.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|recipes (5.4.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|storage (5.0.0) from forestry_1.10.2-5.2.17.368.jar
		* ForestryAPI|world (2.1.0) from forestry_1.10.2-5.2.17.368.jar
		* railcraft:API|core (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|bore (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|carts (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|charge (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|crafting (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|events (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|fuel (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|helpers (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|items (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|locomotive (2.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|signals (3.0.0) from Railcraft_1.10.2-10.0.1.jar
		* RailcraftAPI|tracks (3.0.0) from Railcraft_1.10.2-10.0.1.jar
```

**Comment by CovertJaguar** [comment] 2017-03-01 09:58
Possibly related to #1074

**Comment by Generalcamo** [comment] 2017-04-27 01:45
Definitely still a thing unfortunately. @CovertJaguar

**Comment by liach** [comment] 2017-04-27 02:03
Same error or just loading API from incompatible classloader?

**Comment by liach** [comment] 2017-04-27 02:05
@Generalcamo I cannot reproduce this issue in my test environment. How did you get that?

**Comment by CovertJaguar** [comment] 2017-04-27 07:27
Uh...it shouldn't be

**Comment by liach** [comment] 2017-04-27 15:20
Isn't this fixed with the latest commit 51749de7a1d28c9cce5bd059979b8635bc3dfedb?

**Comment by Generalcamo** [comment] 2017-04-27 15:24
Right I mixed this one up.

**Closed as completed by Generalcamo** 2017-04-27 15:24 UTC
Labels: bug, medium priority, mod compatibility

**Comment by liach** [comment] 2017-04-27 15:26
@CovertJaguar Will you releasee 10.1.2 then?
