### ISSUE TITLE
Crash on startup forge 2796

### ISSUE THREAD

**Issue by navaroneee** [Railcraft/Railcraft#1587] opened 2018-12-25 17:55 UTC
**Description of the Bug**
Crash on startup

**To Reproduce**
Start client or server witout forestry (is it dependencie?)

**Environment**
 - Version Railcraft 12.0.0-beta-1
 - Forge version:2796.

**Additional context**
Crash log
https://pastebin.com/U49EG70r

**Comment by liach** [comment] 2018-12-25 18:19
Dupe of #1578

**Closed as completed** 2018-12-25 18:19 UTC
Labels: duplicate
