### ISSUE TITLE
Tank Cart Detector not detecting tank cart.

### ISSUE THREAD

**Issue by droctogonapus** [Railcraft/Railcraft#1226] opened 2017-05-26 22:52 UTC
The Railcraft tank cart is being detected by the item detector, but not the Tank Cart Detector.  Regardless if there's liquid in it or not.

Only mods I had when testing this out are:
CodeChickenCore 1.10.2-2.4.1-103
CodeChickenLib 1.10.2-2.5.8.255
jei 1.10.2-3.14.419
NotEnoughItems 1.10.2-2.1.3.220
Railcraft 1.10.2-10.1.2

![2017-05-26_17 51 21](https://cloud.githubusercontent.com/assets/11169771/26515017/003cc1c2-423c-11e7-89ba-8f2b0a6f0506.png)

**Comment by Generalcamo** [comment] 2017-05-27 00:45
Medium Priority because this basically makes an entire block useless.

@droctogonapus Can you test without NEI, CodeChickenCore, and CodeChickenLib?

**Comment by liach** [comment] 2017-05-27 00:50
@Generalcamo We should test lol

**Comment by Generalcamo** [comment] 2017-05-27 01:01
Confirmed independently.

**Comment by liach** [comment] 2017-06-07 07:45
Wait it works at intended. I cannot reproduce this "bug", this detector is totally fine.

**Comment by liach** [comment] 2017-06-07 07:46
I am going to close this. The detector works, you need to make sure the mode is right.

**Closed as completed by liach** 2017-06-07 07:46 UTC
Labels: bug, medium priority, can't reproduce, carts

**Comment by CovertJaguar** [comment] 2017-06-07 15:12
An argument could perhaps be made that the default mode is wrong?
