### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by KroniQPlayer** [Railcraft/Railcraft#1859] opened 2019-07-13 00:07 UTC
Got th following error on server boot for my modpakc

ul 12, 2019 5:10:29 PM io.netty.util.ResourceLeakDetector reportUntracedLeak
SEVERE: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enable advanced leak reporting to find out where the leak occurred. To enable advanced leak reporting, specify the JVM option '-Dio.netty.leakDetection.level=advanced' or call ResourceLeakDetector.setLevel() See http://netty.io/wiki/reference-counted-objects.html for more information.

Upon following those directions it was discovered taht railcraft was the likely culprit as refenrenced in the following pastebin

https://pastebin.com/GVMLHG1K

**Comment by RevolutionUK** [comment] 2019-07-15 14:59
Just to add onto KroniQPlayer's issue, experiencing the same memory leak. https://pastebin.com/uRcpes8t

Version of Railcraft: railcraft-12.0.0.jar
Minecraft Version: 1.12.2
Forge Version: forge-14.23.5.2838
Using the Twitch client

Additional mods installed:
AppleSkin-mc1.12-1.0.9.jar
appliedenergistics2-rv6-stable-6.jar
badwithernocookiereloaded-1.12.2-3.3.16.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BetterAdvancements-1.12.2-0.1.0.77.jar
BetterFps-1.4.8.jar
BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar
blockcraftery-1.12.2-1.3.1.jar
Botania r1.10-361.jar
BrandonsCore-1.12.2-2.4.16.207-universal.jar
CarryOn MC1.12.2 v1.12.2.jar
Chisel-MC1.12.2-0.2.1.35.jar
chiselsandbits-14.33.jar
Clumps-3.1.2.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar
CoFHCore-1.12.2-4.6.3.27-universal.jar
CoFHWorld-1.12.2-1.3.1.7-universal.jar
CommonCapabilities-1.12.2-2.4.4.jar
CompactSolars-1.12.2-5.0.18.341-universal.jar
CookingForBlockheads_1.12.2-6.4.71.jar
CraftTweaker2-1.12-4.1.19.jar
CTM-MC1.12.2-0.3.3.22.jar
CyclopsCore-1.12.2-1.4.0.jar
deepresonance-1.12-1.8.0.jar
DefaultOptions_1.12.2-9.2.8.jar
diethopper-1.1.jar
Draconic-Evolution-1.12.2-2.3.23.345-universal.jar
ElecCore-1.12.2-1.9.452.jar
energyconverters_1.12.2-1.3.0.15.jar
ExtremeReactors-1.12.2-0.4.5.67.jar
FastFurnace-1.12.2-1.3.1.jar
FastLeafDecay-v14.jar
FastWorkbench-1.12.2-1.7.2.jar
flatcoloredblocks-mc1.12-6.8.jar
foamfix-0.10.5-1.12.2.jar
Forgelin-1.8.3.jar
ForgeMultipart-1.12.2-2.6.1.81-universal.jar
FTBLib-5.4.3.129.jar
FTBQuests-1.7.2.187.jar
generators-0.9.20.12-mc1.12.2.jar
gravestone-1.10.1.jar
ImmersiveEngineering-0.12-89.jar
industrialcraft-2-2.8.109-ex112.jar
industrialforegoing-1.12.2-1.12.12-236.jar
IntegratedDynamics-1.12.2-1.0.17.jar
IntegratedTunnels-1.12.2-1.6.10.jar
inventorysorter-1.12.2-1.13.3+57.jar
IronBackpacks-1.12.2-3.0.8-12.jar
ironchest-1.12.2-7.0.69.845.jar
ItemFilters-1.0.3.12.jar
jei_1.12.2-4.15.0.268.jar
journeymap-1.12.2-5.5.4.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
malisiscore-1.12.2-6.5.1.jar
Mantle-1.12-1.3.3.55.jar
mcjtylib-1.12-3.5.3.jar
MobGrindingUtils-0.3.13.jar
modnametooltip_1.12.2-1.10.1.jar
Morpheus-1.12.2-3.5.106.jar
MouseTweaks-2.10-mc1.12.2.jar
MrTJPCore-1.12.2-2.1.4.43-universal.jar
mysticallib-1.12.2-1.3.1.jar
NetherPortalFix_1.12.1-5.3.17.jar
NoMoreRecipeConflict-0.13(1.12.2).jar
OpenComputers-MC1.12.2-1.7.4.153.jar
Pam's HarvestCraft 1.12.2zd Surprise for Yogcast.jar
pneumaticcraft-repressurized-1.12.2-0.11.3-366.jar
ProjectRed-1.12.2-4.9.3.116-Base.jar
ProjectRed-1.12.2-4.9.3.116-compat.jar
ProjectRed-1.12.2-4.9.3.116-fabrication.jar
ProjectRed-1.12.2-4.9.3.116-integration.jar
ProjectRed-1.12.2-4.9.3.116-lighting.jar
ProjectRed-1.12.2-4.9.3.116-mechanical.jar
ProjectRed-1.12.2-4.9.3.116-world.jar
railcraft-12.0.0.jar
reauth-3.6.0.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
refinedstorage-1.6.14.jar
refinedstorageaddons-0.4.4.jar
rftools-1.12-7.71.jar
SGCraft-2.0.1.jar
SimplyJetpacks2-1.12.2-2.2.12.65.jar
stg-1.12.2-1.2.3.jar
TConstruct-1.12.2-2.12.0.157.jar
tesla-core-lib-1.12.2-1.0.15.jar
Thaumcraft-1.12.2-6.1.BETA26.jar
ThaumicJEI-1.12.2-1.6.0-27.jar
theoneprobe-1.12-1.4.28.jar
ThermalCultivation-1.12.2-0.3.3.12-universal.jar
ThermalDynamics-1.12.2-2.5.5.21-universal.jar
ThermalExpansion-1.12.2-5.5.4.43-universal.jar
ThermalFoundation-1.12.2-2.6.3.27-universal.jar
ThermalInnovation-1.12.2-0.3.3.12-universal.jar
TipTheScales-1.12.2-1.0.4.jar
topaddons-1.12.2-1.11.0.jar
UniDict-1.12.2-2.9.2.jar
WanionLib-1.12.2-2.2.jar
zerocore-1.12.2-0.1.2.8.jar

I'm on a server with around 8 other people, at least 2 of us who have used Railcraft are experiencing this. Other users are unaffected. The only thing I've used is the Tanks and Steam Locomotive. So perhaps its linked to these blocks?

Happy to post more info if needed

**Comment by Phantum** [comment] 2019-07-24 22:37
Also have this happening on my server, I'm running spongeforge with a handful of other plugins.
https://gist.github.com/Phantum/834a8892e6b7ef4d28e8dfa08338a52a

**Comment by benjaminthegreat** [comment] 2019-07-29 20:17
Yeah I'm not sure if they're the culprit but I started having memory leak issues after building several steam boilers. I'm running FTB Revelation 3.0.1, and I'd be happy to give more information too. I'm not sure if they're actually the culprit though, because I also built an Extreme Reactors turbine to use the steam at the same time.

**Comment by RevolutionUK** [comment] 2019-07-30 19:10
Update from my end, I removed the Tanks from my chunks and replaced with another mods tanks and the memory leak has stopped. Considering Benjaminthegreat is having the same issue with steam boilers probably something to with tanks and liquid/gas storage?

**Comment by Phantum** [comment] 2019-07-30 21:03
I believe its anything to do with an inventory. was getting them from locomotives and a few other things as well.

**Comment by CovertJaguar** [comment] 2020-07-26 17:46
Hmm... I use bytebuf in several places. I didn't know you need to release them. Will check.

**Comment by AveoCross** [comment] 2021-05-30 11:03
Problem still exists. I have the exact same logs after any player logs onto server near Railcraft tank on map.

**Comment by CovertJaguar** [comment] 2022-06-16 23:02
Duplicate of #2019

**Closed as completed by CovertJaguar** 2022-06-16 23:02 UTC
