### ISSUE TITLE
1.12.2 Crash 

### ISSUE THREAD

**Issue by AkuzeTR** [Railcraft/Railcraft#1581] opened 2018-12-25 15:02 UTC
**Crash 1.12.2**

Here is a bin file 

https://pastebin.aquilenet.fr/?21c88e9b2fcea7ed#q6SMGoICnjZclDmBtQAwxjChI49t59Guc4pJQBcPido=

**Comment by Yzelast** [comment] 2018-12-25 16:29
looks like installing forestry fix the crash...

**Comment by liach** [comment] 2018-12-25 18:20
Dupe of #1578

**Closed as completed** 2018-12-25 18:21 UTC
Labels: duplicate
