### ISSUE TITLE
Steam boiler takes in more water than it says it can.

### ISSUE THREAD

**Issue by truehunterethan** [Railcraft/Railcraft#1722] opened 2019-02-17 03:01 UTC
**Description of the Bug**
When inputing water into a 3x3x3 steam boiler with a 3x3 solid fuel firebox, the boiler up to 108,000 mb of water, way more than the said 6 buckets.

**To Reproduce**
make a steam boiler.
input more than 6 water buckets in it, and it now has more water than the GUI says it can.

**Expected behavior**
it should only hold 6 buckets of water
**Screenshots & Video**
https://imgur.com/a/JUHZhbN

**Logs & Environment**
https://pastebin.com/waJNJJWR
 - Full log: 

 - Crash report (If available): 

**Additional context**

**Comment by liach** [comment] 2019-02-17 06:24
Duplicate of #1567

**Closed as completed by liach** 2019-02-17 06:24 UTC
Labels: duplicate
