### ISSUE TITLE
Minecarts of various types randomly disappearing

### ISSUE THREAD

**Issue by iambob314** [Railcraft/Railcraft#585] opened 2015-04-17 23:29 UTC
(Possibly related to #433.)

At least three times now, in two separate areas, a portion of a Railcraft-linked train has vanished without a trace. The first two times only the locomotive disappeared, while the third time the locomotive and some vanilla minecarts-with-chest also disappeared.

In the first two cases, the train's route was fully chunkloaded, but the chunkloaders may have run out. In the third case, the train included a world anchor cart, which did not run out (the world anchor cart was not among the vanishing carts). In all cases, there was no physical damage to the area (i.e., no creeper explosions, etc.)

Unfortunately, we don't have much more information yet; I'll update this issue if we learn more.

**Comment by CovertJaguar** [comment] 2015-04-18 01:36
There are known issues with vanilla entity handling that have existed for as long as Railcraft has. No one has been able to identify the root cause of the issue, only that is affects all moving entities and only occurs when a chunk unloads/loads.

**Comment by liach** [comment] 2017-01-07 20:39
This looks like an issue with NBT serialization.

**Comment by Georggi** [comment] 2017-04-15 17:48
If it is going to be resolved, is it possible to release 1.7.10 version of this?

**Comment by liach** [comment] 2017-04-15 23:57
not likely

**Comment by liach** [comment] 2017-07-16 16:54
Try disabling dormant chunk cache.

**Comment by CovertJaguar** [comment] 2017-07-16 21:48
This issue existed before the dormant chunk cache existed, its been around since the earliest days of Railcraft. The original Forge PR may have fixed the entity issues, but I'm pretty sure the new one they decided to use won't.

**Comment by liach** [comment] 2017-12-10 18:06
https://github.com/MinecraftForge/MinecraftForge/issues/1642
There has been a forge ticket on this long ago, but it was pretty much ignored.

**Comment by liach** [comment] 2017-12-10 18:10
Also, see 
https://bugs.mojang.com/browse/MC-12194
http://www.minecraftforum.net/forums/minecraft-java-edition/survival-mode/2621802-minecarts-disappearing-in-1-8

**Comment by liach** [comment] 2018-09-26 03:17
I guess MinecraftForge/MinecraftForge#5160 might handle that.

**Comment by aikar** [comment] 2018-09-26 03:43
@liach yes 5160 will greatly help with lots of entity disappearance/rollback issues.

**Comment by liach** [comment] 2018-09-26 03:57
Thanks @aikar :heart: Turns out bukkit/spigot can actually help mods instead of "bringing conflicts!" because of your effort!

**Comment by Generalcamo** [comment] 2018-09-27 05:46
The PR was merged in, this needs testing with the latest Forge Versions that include this PR

**Comment by CovertJaguar** [comment] 2018-11-01 01:32
Closing until we receive a positive report that this still happens.

**Closed by CovertJaguar** 2018-11-01 01:32 UTC
Labels: bug, carts, high priority, needs verification, not railcraft
