### ISSUE TITLE
Rolling machine recipes are not copied to crafting tables

### ISSUE THREAD

**Issue by Shandoo94** [Railcraft/Railcraft#1604] opened 2018-12-28 20:10 UTC
**Description of the Bug**
When the factory module is disabled, rolling machine recipes are not copied to the crafting table.
~When disabeling the Factory module, things like tracks still use rails in their recipes. In this configuration the tracks would not be normally craftable. Also the rolling machine doesn't show recipes in JEI.~

**To Reproduce**
1. Disable Factory Module in Config
2. Look up recipes in JEI

**Expected behavior**
Rails, etc. craftable through crafting table.
~Alternative recipes that don't utilize items only craftable through the factory module.~

**Environment**
Railcraft 12.0.0-beta2
forge 14.23.2796

**Comment by CovertJaguar** [comment] 2018-12-29 01:59
I believe disabling the Factory, and therefor the Rolling Machine, dumps the Rolling Machine recipes into the vanilla Workbench.

You'd have explicitly enable vanilla style track recipes or disable the rail items for them to not be used.

**Comment by Shandoo94** [comment] 2018-12-29 07:47
If the Factory Module is disabeled the rails are only craftable through tracks as seen in the screenshot below. A couple of other items like the large charge wire spool are also not craftable, even with factory module enabled. At least I don't see a recipe in JEI.

![2018-12-29_08 39 35](https://user-images.githubusercontent.com/21018028/50535052-a6c3a780-0b45-11e9-9ee4-87152e2dffa0.png)

Maybe the issue is, that a few recipes are missing in general and therefore there are no recipes in the rollingmachine to be pushed onto the crafting bench?

**Comment by liach** [comment] 2018-12-29 08:03
jei display isn't related to actual recipes. this is working as intended.

**Comment by Shandoo94** [comment] 2018-12-29 09:03
So how do I craft rails then if I can't see the recipes in JEI? Just using the rollingmachine patterns from the official wiki in the craftingtable doesn't work.
Is it intended that I don't see the recipes of the rolling machine? If yes, why?

**Comment by liach** [comment] 2018-12-29 17:31
If you disable factory, I don't think you can see rolling machine recipes any more. Now, rolling machine recipes are dependent on the factory module. I guess the recipe migration will be broken, so I will get another title for this issue.

**Comment by CorruptData404** [comment] 2018-12-30 01:31
The rolling machine recipes aren't being shown at all, with or without factory disabled. I'm running on default config with factory enabled. The "Show Recipes" in the both rolling machines also does nothing.

isolated the mod along with JEI and getting same problem. 
![2018-12-29_17 30 31](https://user-images.githubusercontent.com/38871274/50543523-86b8d600-0b8f-11e9-8fe7-5dfc54ecc357.png)

**Comment by Shandoo94** [comment] 2018-12-30 08:11
Yes, it is the same for me.

**Comment by draxxris** [comment] 2019-01-02 04:04
Bug is present regardless of factory module settings. Using 12-beta2

**Comment by CovertJaguar** [comment] 2019-01-02 20:42
It's simple. The Rolling Machine doesn't have a working JEI recipe handler right now.

It was replaced with a "//TODO add this later" line when the recipe manager got scrapped and rewritten.

It was either that or no release on Christmas.

**Comment by CovertJaguar** [comment] 2019-01-03 00:42
I haven't tested the recipe migration, but the other issues should be fixed by 307ec2f8ce0cb504e829ca29d9e9171f085fce7a

**Closed as completed** 2019-01-18 02:13 UTC
Labels: bug, medium priority
