### ISSUE TITLE
Wye Tracks aren't showing up

### ISSUE THREAD

**Issue by 4498Lincoln** [Railcraft/Railcraft#1817] opened 2019-04-15 13:32 UTC
I don't have a crash report to provide but the wye tracks on this mod aren't showing up. I tried JEI and crafting but still nothing. I am using the latest (I think) Railcraft from curseforge and all of my modules are enabled in both my Railcraft modules.cfg and ingame interface on modules.

Mods: 
![image](https://user-images.githubusercontent.com/49529648/56136714-2f752080-5f48-11e9-803a-21ecc836327e.png)

**Comment by LuigiHutch** [comment] 2019-04-15 13:37
Basically a duplicate of https://github.com/Railcraft/Railcraft/issues/1364. Whack a piece of track with a spike maul

**Comment by liach** [comment] 2019-04-15 13:42
Look at your advancements bro. The advancement with the turnout track icon tells you how to make a wye track :trollface:

**Closed as completed by liach** 2019-04-15 13:42 UTC
Labels: question or discussion

**Comment by 4498Lincoln** [comment] 2019-04-15 13:45
> 
>
> Basically a duplicate of #1364. Whack a piece of track with a spike maul
Thanks, I'm the inexperienced user who just downloads stuff I randomly see on curseforge without thinking.
