### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by maverickx29** [Railcraft/Railcraft#1021] opened 2016-11-22 16:06 UTC
This is a cross mod bug, and I am not sure if it is on your end or Immersive Engineering's end, and I'm posting it for both of you. Playing on version 1.10.2-10.0.0 in the direwolf pack, I made creosote bottles to speed up making the treated wood because they stack, however using more then one at a time results in 1 less then double the creosote bottles to be in the crafting table, waiting to be crafted again. I believe it has something to do with the empty bottles that are suppose to be showing up and instead are stacking, because this can go on well past 16 (the normal stack max), even 64. It is repeatable, just make sure u put more then one creosote bottle at a time in the crafting window, if you use just one it appears to work as intended.

**Comment by Ristellise** [comment] 2016-11-23 05:30
duplicate. please use ths search function next time.

**Comment by Forecaster** [comment] 2016-11-23 09:16
Duplicate of #1012

**Closed as completed by Forecaster** 2016-11-23 09:16 UTC
Labels: duplicate
