### ISSUE TITLE
[1.10.2-10.1.2] Recipes containing creosote containers don't allow buckets of creosote

### ISSUE THREAD

**Issue by MalkContent** [Railcraft/Railcraft#1207] opened 2017-05-16 16:42 UTC
I glanced at the code a bit and I assume that the recipes are intended to accept them. Tried to find why the don't, but didn't find the end of that rabbithole.
Best guess: Bucket gets added only after the recipes are set up.

**Comment by liach** [comment] 2017-05-16 20:18
That is intentional. CJ opened a pull request to forge but was not accepted because he failed to maintain it.

**Comment by MalkContent** [comment] 2017-05-16 21:53
oh. strange. okay then :) i mean i tried this in a vanilla + railcraft only setting with the universal creosote bucket that was added by rc so i'm genuinely curious as to what the issue is.

**Comment by liach** [comment] 2017-05-16 23:29
The issue is with fluid containers not recognized in crafting recipe.

**Comment by Generalcamo** [comment] 2017-05-16 23:40
There are some plans to "fix" this with our own implementation of the prior pull request. I'm sure CovertJaguar can explain more though.

**Comment by liach** [comment] 2017-05-17 00:06
https://github.com/MinecraftForge/MinecraftForge/pull/3332

**Comment by Generalcamo** [comment] 2017-05-19 14:34
Affects Railcraft recipes as well. This is a bit more important than I thought.

**Comment by liach** [comment] 2017-08-03 03:54
We can create a custom recipes class for this for now.

**Comment by liach** [comment] 2017-09-08 03:13
Fixed in that commit above.

**Closed as completed by liach** 2017-09-08 03:13 UTC
Labels: bug, medium priority, inventory
