### ISSUE TITLE
Missing engines

### ISSUE THREAD

**Issue by reveal-ux** [Railcraft/Railcraft#1940] opened 2020-04-23 19:33 UTC
Why did you remove engines which were in Railcraft mod? Mod is very great, but I really feel lack of this. Please add some engines like Industrial Steam Engine or maybe something imaginated by you. Please rewrite answer to me.

**Comment by Su5eD** [comment] 2020-04-23 20:21
#1388

**Comment by Forecaster** [comment] 2020-04-23 20:29
Duplicate of #1388

**Closed as completed by Forecaster** 2020-04-23 20:29 UTC
