### ISSUE TITLE
[1.10.2] All configs except modules are blank

### ISSUE THREAD

**Issue by SpartanSamuel** [Railcraft/Railcraft#1024] opened 2016-11-23 21:45 UTC
Of all the config files it comes with (blocks, client, entities, items, modules, railcraft), modules is the only file that's not completely empty. Is this a bug, or does it generate as I play? I'm on a pretty fresh world and haven't played for more than a night or two in-game so far.

Also, I'd like to use the configs to disable redundant ores so that I'm not working with 3x different kinds of copper but the only place I see that disables RC ore generation is simply disabling the World module entirely. There's no options to disable specific ores, or even quality of ores (looking at you poor ores), not to mention adjusting the spawn chance, height, or density of clusters.

Are these features currently planned to be added at some point?

**Comment by tomelfring** [comment] 2016-11-23 22:50
Duplicate of #984

**Comment by SpartanSamuel** [comment] 2016-11-23 22:52
Ah, thanks for that! Looks like I missed the thread. There's still the feature request as well.

**Comment by Forecaster** [comment] 2016-11-24 12:33
Please put the feature in it's own ticket with the appropriate title

**Closed as completed by Forecaster** 2016-11-24 12:33 UTC
Labels: duplicate
