### ISSUE TITLE
Massive Lag and Crash [Worldgen Cascading LAG]

### ISSUE THREAD

**Issue by Crosus97** [Railcraft/Railcraft#1667] opened 2019-01-20 00:16 UTC
**Description of the Bug**
The railcraft create a CascadinLAG on world gen

**To Reproduce**

1. use last version of forge server
2. play with friends
3. when railcraft need to create a chunk in console you saw

**Expected behavior**
some times, the load its soo big and the server crash
you can see it in the log adjunt

**Screenshots & Video**
N/A

**Logs & Environment**
https://gist.github.com/Crosus97/cba59eaa39545ec77bff5484940fc99d

**Additional context**
any solution?

**Comment by liach** [comment] 2019-01-20 02:05
Duplicate of #1474. Closing this issue, but if you have any crash report for your server, feel free to upload here and ask me for help to resolve it.

**Closed as completed by liach** 2019-01-20 02:05 UTC
Labels: duplicate
