### ISSUE TITLE
[1.10.2] Missing textures in jei and placed blocks

### ISSUE THREAD

**Issue by YOYOK9** [Railcraft/Railcraft#985] opened 2016-11-01 16:45 UTC
I've noticed that a few Items/Blocks are missing textures while looking through JEI. I do Have optifine installed. 

Client Console: 
https://gist.github.com/YOYOK9/4d529f6e3ca60ff6cc555a7a3c53cfb8

Picture of JEI: 
http://puu.sh/s2XBQ/44423406a4.jpg

MC: 1.10.2
Forge: 2117
Railcraft: 1.10.2-10.0.0
JEI: 1.10.2-3.13.0.338

**Comment by GirafiStudios** [comment] 2016-11-01 16:52
Have you tried without Optifine? Pretty sure that is causing it :)

**Comment by Viteksnake** [comment] 2016-11-01 16:54
Yes, it is because Optifine. Anyone know how to fix it?

**Comment by liach** [comment] 2016-11-01 17:56
You might need to report this to optifine since railcraft has a custom TextureAtlasSheet.

**Comment by karikusa** [comment] 2016-11-01 18:56
I am also troubled out the same symptoms!
Optifine the Do if important somehow so MOD, I've been reported to Optifine!
Since RailCraft is a very fun, I hope successfully get to correspond
By the way, I am writing with a translation site because it does not handle English in Japanese. I hope are transmitted well, but ...

**Comment by YOYOK9** [comment] 2016-11-01 19:03
I have also reported this issue to the optifine github:
https://github.com/sp614x/optifine/issues/310

If I here back will let you all know!

**Comment by CovertJaguar** [comment] 2016-11-01 21:58
Duplicate of #924

**Closed as completed by CovertJaguar** 2016-11-01 21:58 UTC
Labels: duplicate

**Comment by CovertJaguar** [comment] 2016-11-01 21:59
If you want to speed up the process...go leave a thumbs up on the Optifine Issue.
