### ISSUE TITLE
[1.12.2] Multiblock tank deletes fluid after its filled 

### ISSUE THREAD

**Issue by thill19** [Railcraft/Railcraft#1625] opened 2019-01-07 01:21 UTC
**Description of the Bug**
Filled the iron tank full of lava it deleted the lava from the drum after it was filled 

**To Reproduce**
Step1: Fill iron tank with lava until its completely full
Step2: iron Tank deletes lava after full

**Expected behavior**
I expected the iron tank to stop accepting lava after it was full

**Comment by CovertJaguar** [comment] 2019-01-08 00:38
Drum?

**Comment by bookerthegeek** [comment] 2019-01-08 04:43
One would assume they were using a drum from extra utilities 2 as a source of the fluid.

**Comment by CovertJaguar** [comment] 2019-01-09 23:59
And how did they get that fluid into the tank?

**Comment by thill19** [comment] 2019-01-13 16:17
i used a fluiduct from thermal expansion

**Comment by thill19** [comment] 2019-01-13 16:18
> One would assume they were using a drum from extra utilities 2 as a source of the fluid.

i was actually using ender tanks for it

**Comment by Nagyur** [comment] 2019-01-13 17:19
Hi! I built a 3*3*4 iron tank with one valve in beta2 filling it with oil in creative mode with buckets the level meter said full after 64 bucket and keep accepting new buckets of oil. It is not deleted but the scale is wrong. After switching to survival mode i can extract the oil i pured in and the scale wont drop untli i get the overflow out. 
Further more all tank size indicate that they are full afer 64 bucket of oil. even the 9*9*8 one.

**Comment by CovertJaguar** [comment] 2019-01-13 20:34
So possibly an issue with the fluid widget.

**Comment by liach** [comment] 2019-01-13 22:46
So this is actually a duplicate of #1567. Moving the talks there.

**Closed as completed by liach** 2019-01-13 22:46 UTC
Labels: bug, needs verification, high priority, machines and structures
