### ISSUE TITLE
Railcraft Crashed on Rightclicking Admin Worldspike Cart and now wont Load

### ISSUE THREAD

**Issue by andrfgs** [Railcraft/Railcraft#1824] opened 2019-04-24 02:34 UTC
I was using railcraft-12.0.0-beta-5.jar on a forge catserver (Catserver CatServer-git-1468a63-Community.jar). 

When I right clicked the admin world spike minecart, the server crashed. From that point onward, whenever I try to launch the server it crashes on load. Here's the log:
https://pastebin.com/YpgXVjaP

**Comment by andrfgs** [comment] 2019-04-24 02:43
Updated the mod and seems to be working fine.

**Comment by liach** [comment] 2019-04-24 02:43
#1759

**Comment by andrfgs** [comment] 2019-04-24 02:51
I am very sorry to report, but after all this bug still persists. The server does load now, but rightclicking the minecart still crashes it.

Now using railcraft-12.0.0.jar, same server.
https://pastebin.com/R1vYU0FV

This also crashed the client.

Using forge 14.23.5.2815 on server
Using forge 14.23.5.2835 on client.

Might be forge version?

**Comment by liach** [comment] 2019-04-24 05:20
duplicate of.#1808

**Closed as completed** 2019-04-24 05:20 UTC
