### ISSUE TITLE
Creosote and capsules issue 1.7.10-9.12.2.0

### ISSUE THREAD

**Issue by DEX47** [Railcraft/Railcraft#1081] opened 2017-02-15 22:49 UTC
Trying to resolve an issue with Railcraft capsules. Apparently no recipe exits that allows capsules to be filled with creosote. The end item, creosote filled capsule, does exist in the game. Does anyone know how to add such thing via  MineTweaker?

**Comment by MauveCloud** [comment] 2017-02-16 00:00
You don't need MineTweaker.
Capsules are from the Forestry mod (made from beeswax or refractory wax), and you can fill them with creosote by putting them in the top slot of a coke oven that has creosote oil in it.  Railcraft is just being weird to define the creosote capsules (and show them in NEI) when Forestry is not installed.  Said capsules have no particular advantage over bottles or other containers of creosote; they're just made from different materials.  Also, iirc capsules usually aren't returned when crafting with them.

**Comment by DEX47** [comment] 2017-02-16 02:57
Your right my mistake. Forest capsules are not working with Railcraft creosote. There is likely some mumbo jumbo mix up with my 140+ mods that are resulting in a crafting recipe issue. That is why I'm asking for a MineTweaker work around. Creosote is also a shared fluid with Immersive Engineering. I can provide a full ist of mods and versions if that will help. It will take some time to write down.

**Comment by MauveCloud** [comment] 2017-02-16 03:17
I'm not sure I can help you in that case, why you need a Minetweaker workaround so much (since there should still be other fluid containers you can use instead), or that this is appropriate to continue discussing in the comments of a GitHub issue for Railcraft, but I do know of a faster way to get a list of mods with versions - see this YouTube video: http://y2u.be/Ipb18wZaPxE

**Comment by DEX47** [comment] 2017-02-16 03:25
I do my best to stamp out glitches and oddities as best I can for my users. There are alternatives to capsules yes. I still put an effort out to making things 100%. My searches pointed me here with like issues. Not sure where the best spot to post is as I'm not sure the origin of the conflict.

**Comment by DEX47** [comment] 2017-02-16 03:48
Any case here is the list.

1.7.10
1.7.10-ExpandedIndustry-15.26.1a.jar
1.7.10_AM2-1.4.0.009.jar
AdvancedRocketry-1.7.10-1.0.4.jar
adventurebackpack-1.7.10-0.8c.jar
AgriCraft-1.7.10-1.5.0.jar
ancientwarfare-2.4.115-beta-MC1.7.10-FULL.jar
AnimationAPI-1.7.10-1.2.4.jar
arcane_engineering-0.2.7.jar
ATG-1.7.10-0.12.0.jar
Automagy-1.7.10-0.28.2.jar
autooredictconv-1.7.10-1.3.1.jar
BetterBoat-1.7.10-1.1.0.jar
BetterFoliage-MC1.7.10-2.0.14.jar
BiblioCraft[v1.11.5][MC1.7.10].jar
BiblioWoods[BiomesOPlenty][v1.9].jar
BigDoors-1.7.10-1.1.0.jar
BigReactors-0.4.3A.jar
BiomesOPlenty-1.7.10-2.1.0.1390-universal.jar
Bookshelf-1.7.10-1.0.4.187.jar
Botania r1.8-249.jar
Carpenter's Blocks v3.3.8.1 - MC 1.7.10.jar
catwalks-2.0.4.jar
Chisel-2.9.5.11.jar
ClockHUD-1.7.10-1.1.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.3-327.jar
CollectiveFramework-1.0.0-132.jar
compactmachines-1.7.10-1.21.jar
ComputerCraft1.75.jar
ComputerCraftEdu1.74.jar
ContentTweaker-1.0.5.jar
CraftTweaker-1.7.10-3.0.11.jar
CrayTokensLite-v0.82-MC1.7.10.jar
CustomNPCs_1.7.10d(21feb16).jar
Decocraft-2.3.6.1_1.7.10.jar
deepresonance-1.1.4.jar
DynamicSurroundings-1.7.10-1.0.5.6.jar
eldritch-empires-091.jar
ElecCore-1.7.10-1.4.294.jar
ElsewhereBorder-1.7.10-1.0.0-5-universal.jar
Enchiridion 2-1.7.10-2.0.2a.jar
EnviroMine-1.3.124.jar
Exotic Birds 1.7.10 - 1.0.3b.jar
ExtraTiC-1.7.10-1.4.6.jar
extrautilities-1.2.12.jar
fastcraft-1.23.jar
FastLeafDecay-1.7.10-1.4.jar
Fireplace-Mod-1.7.10.jar
Fluxed-Core-MC1710-1.0.9.jar
Forbidden Magic-1.7.10-0.575.jar
forestry_1.7.10-4.2.16.64.jar
gadomancy-1.7.10-1.0.7.3.jar
glass_shards_mc1.7.10-1.5.2.jar
GraveStone-2.16.1.jar
Grim3212-Core-1.7.10.jar
GrimoireOfGaia3-1.7.10-1.2.7.jar
growthcraft-1.7.10-2.5.2-complete.jar
HardcoreEnderExpansion  MC-1.7.10  v1.8.6.jar
hopperductmod-1.7.10-1.3.2.jar
ice_shards_mc1.7.10-1.3.jar
ImmersiveEngineering-0.7.7.jar
immibis-core-59.1.4.jar
InventoryTweaks-1.59-dev-152.jar
journeymap-1.7.10-5.1.4p1-fairplay.jar
KoreSample-1.7.10-1.3.2.jar
LavaMonsters-1.7.10-2.2.1.jar
LibVulpes-1.7.10-0.1.12-universal.jar
malisiscore-1.7.10-0.14.3.jar
malisisdoors-1.7.10-1.13.2.jar
Mantle-1.7.10-0.3.2b.jar
Mariculture-Deluxe-1.7.10-1.2.4.2a.jar
mcjtylib-1.8.1.jar
mdecore-1.0.jar
Metallurgy-1.7.10-4.0.6.80.jar
MetallurgyCore-1.7.10-4.0.4.18.jar
MineFactoryReloaded-[1.7.10]2.8.1-174.jar
MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar
Mo' Zombies 2.1.1.jar
modlist.txt
ModTweaker2-0.9.6.jar
ModularPowersuits-0.11.1.109.jar
MoreEnchantments-1.7.10-1.3.2.1.jar
Morpheus-1.7.10-1.6.10.jar
MyEssentials-Core-1.7.10-1.18r-universal.jar
MyPermissions-1.7.10-66-dev.jar
MyTown2-1.7.10-0.5.0b.jar
NomadicTents[1.7.10]-1.11.jar
NotEnoughItems-1.7.10-1.0.5.120-universal.jar
Numina-0.4.1.104.jar
OpenBlocks-1.7.10-1.5.1.jar
OpenModsLib-1.7.10-0.9.1.jar
OpenModularTurrets-1.7.10-2.2.9-232.jar
Pam's Clay Spawn 1.7.10b.jar
Pam's Harvest the Nether 1.7.10a.jar
Pam's HarvestCraft 1.7.10Lb.jar
PChan3Mods-0.7(1.7.10).jar
Peripherals++-1.3.6.jar
PPP
Practical-Logistics-1.7.10-0.2.4.jar
ProjectRed-1.7.10-4.7.0pre12.95-Base.jar
ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar
ProjectRed-1.7.10-4.7.0pre12.95-World.jar
ProjectZulu-1.7.10-1.4c2.jar
PvPTime-1.0.6.jar
Railcraft_1.7.10-9.12.2.0.jar
RefinedRelocation-mc1.7.10-1.1.28.jar
reptilemod-1.7.10-2.5.6-10.jar
rftools-4.23.jar
roguelike-1.7.10-1.5.0b.jar
RunicDungeons-1.1.7b.jar
ScottsTweaks-1.7.10-1.3.1.jar
SGCraft-1.11.3-mc1.7.10.jar
SonarCore-1.7.10-1.1.3.jar
SpecialMobs-1.7.10-3.2.2.jar
StorageDrawers-1.7.10-1.10.8.jar
StorageDrawers-BiomesOPlenty-1.7.10-1.1.1.jar
Tainted-Magic-r7.6.jar
TConstruct-1.7.10-1.8.8.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThaumcraftMobAspects-1.7.2-2A.jar
Thaumic-Dyes-[1.7.10] 1.5.1-0.jar
ThaumicExploration-1.7.10-1.1-53.jar
thaumichorizons-1.7.10-1.1.9.jar
ThermalDynamics-[1.7.10]1.2.0-171.jar
ThermalExpansion-[1.7.10]4.1.4-247.jar
ThermalFoundation-[1.7.10]1.2.5-115.jar
TravellersGear-1.7.10-1.16.6.jar
tubestuff-59.0.4.jar
twilightforest-1.7.10-2.3.7.jar
UBCOres-1.7.10-0.2.9.4.jar
UndergroundBiomesConstructs-1.7.2-0.7.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
Waystones-mc1.7.10-1.0.4.jar
Wild-Caves-Mod-1.7.10.jar
witchery-1.7.10-0.24.1.jar
WitchingGadgets-1.7.10-1.1.10.jar
wolfarmor-1.3.0.1.jar
worldedit-forge-mc1.7.10-6.1.1-dist.jar
WR-CBE-1.7.10-1.4.1.9-universal.jar
[1.7.10]StartingInventory-universal-1.7.10.r03.jar

**Comment by liach** [comment] 2017-03-10 17:01
@DEX47 Can you fill them with empty capsules in coke oven? That's the way to fill it as far as I know.

**Comment by DEX47** [comment] 2017-03-13 05:05
Negative liach, that function seems to have vanished for all interactions between all capsules types and creosote.

**Comment by liach** [comment] 2017-03-13 05:09
Thanks for the info.

**Comment by liach** [comment] 2017-03-13 23:31
![2017-03-13_16 29 43](https://cloud.githubusercontent.com/assets/7806504/23879456/6a1bea08-080a-11e7-9882-9ada144aed59.png)
Well, I can get creosote capsules. So I cannot reproduce this.

**Comment by liach** [comment] 2017-03-13 23:46
Dupe of #766.

**Closed as completed by liach** 2017-03-13 23:46 UTC
Labels: duplicate, bug, low priority, can't reproduce
