### ISSUE TITLE
SpongeForge Cross Post

### ISSUE THREAD

**Issue by bookerthegeek** [Railcraft/Railcraft#1638] opened 2019-01-11 06:07 UTC
## Heyo
Hello! Love the mod. Was building a pack and noticed that it crashes while starting if SpongeForge is involved. (Yes I know, SpongeForge not supported and all that.) Just thought you should know. Also it is posted over on the Sponge GitHub [HERE](https://github.com/SpongePowered/SpongeForge/issues/2540)

### To Reproduce
1. Install Forge, Railcraft and SpongeForge. 
2. Start Minecraft.
3. Get Crash Report

### Expected behavior
Not to crash?

### Logs & Environment
- [Crash Report](https://gist.github.com/bookerthegeek/64d60504f59e315b4f51aa772ce1e7cb)

### Additional context 
Important Versions:
- Railcraft | 12.0.0-beta-4
- SpongeForge | 1.12.2-2768-7.1.4
- Forge | 14.23.5.2807

**Comment by liach** [comment] 2019-01-11 07:38
Duplicate of #1607

**Closed as completed by liach** 2019-01-11 07:38 UTC
Labels: duplicate
