### ISSUE TITLE
[9.12.2.0] Steam Turbine not output RF energy

### ISSUE THREAD

**Issue by Cronosus** [Railcraft/Railcraft#1199] opened 2017-05-11 22:14 UTC
Hello
we have problem with RC 9.12.2.0 .. (both MP and SP)
i use only RF-powered mods, and steam turbine is now totally useless, because not output RF energy
And if it output EU, then not found working way to convert EU to RF.

Are you still fixing things in 1.7.10?
thanks in advance

**Comment by LuigiHutch** [comment] 2017-05-11 22:45
Duplicate of https://github.com/CovertJaguar/Railcraft/issues/182. Use Steam engines if you want RF production. The Steam Turbine is desigined only intended for electricity production so EU or charge, RF is not electricity!

**Closed as completed** 2017-05-11 23:20 UTC

**Comment by Cronosus** [comment] 2017-05-12 16:58
ok, thanks for info
