### ISSUE TITLE
Tank/Boiler GUI glitches: tanks and temperature scaling mismatchs.

### ISSUE THREAD

**Issue by alwaeles** [Railcraft/Railcraft#1567] opened 2018-12-16 15:42 UTC
**Description of the Bug**
In both tanks and boilers GUIs, the scale and the max of temperature, fluid amount, etc. are wrong.

**To Reproduce**
1. Build a HP steam boiler,
2. Make it heating,
3. Look the steam, water and temperature levels...

**Expected behavior**
The tank displays when the boiler is realy full, and not less-than-half full...
The temperature display doesn't get overlapped over some other textures...

**Screenshots & Video**
![https://axeland.re/2A3h7d9](https://axeland.re/2A3h7d9)
![https://axeland.re/2A0lDcm](https://axeland.re/2A0lDcm)
[![Boiler Bug](https://img.youtube.com/vi/TTc39PlIci0/0.jpg)](https://www.youtube.com/watch?v=TTc39PlIci0)

**Environment**
 - Railcraft 12.0.0-alpha-9
 - Forge 14.23.5.2780
 - I don't thing it's a mod conflict...

**Additional context**
_None_

**Comment by liach** [comment] 2018-12-16 19:29
err, this involves the one probe mod. please don't blame railcraft

**Comment by alwaeles** [comment] 2018-12-16 20:07
If it is caused _only_ by One Probe Mod, why the boiler says full and nothing gets out with a pipe connected to the boiler? Maybe because it is not really full. It's only a GUI mistake, but when One Probe says it's half full, the steam magically goes out, even that the boiler GUI says it's full since a while...

**Comment by liach** [comment] 2018-12-16 20:14
the other issue is #1551

**Comment by liach** [comment] 2018-12-16 20:15
which is the same as your broken fluid transfer description.

**Comment by KillTyrant** [comment] 2018-12-16 20:24
Best bet would be to disable one probe and see if the issue still exists

**Comment by alwaeles** [comment] 2018-12-16 21:09
Tested on a almost vanilla instance:

### Mods installed:

* Minecraft Forge 14.23.5.2780,
* Railcraft 12.0.0-alpha-9
* Buildcraft 7.99.19 (don't say this is the cause, it does the same with Thermal Dynamics)

### Result:

[Check it on YouTube](https://www.youtube.com/watch?v=TTc39PlIci0)

**Comment by liach** [comment] 2018-12-16 21:19
1. Try in 1.7 and see if the tank auto pushes content to adjacent blocks like the pipe.
2. Try with wooden fluid pipe and a redstone engine powering the pipe.

Please help me test these two and then I can identify the cause and make a proper fix for the issue.

**Comment by CovertJaguar** [comment] 2018-12-16 21:23
It should work on anything with a FluidHandler that accepts input. I don't know about pipes, but a BC Tank next to the tank of the Boiler _should_ for sure be filled.

https://github.com/Railcraft/Railcraft/blob/d7af7f9be3cc0bd892a1a3ed10f76f3ffcd2680d/src/main/java/mods/railcraft/common/blocks/multi/TileBoiler.java#L237-L240

**Comment by alwaeles** [comment] 2018-12-16 21:44
I added The One Probe and TOP Addons which _displays_ the real content of the tanks then I waited a bit and I recorded...
[This is the record](https://www.youtube.com/watch?v=nCEoxUIsNA4)

**Comment by CovertJaguar** [comment] 2018-12-17 19:47
I would guess that the most likely cause is a mismatch on tank capacity for the client and server.

**Comment by alwaeles** [comment] 2018-12-17 19:53
Probably

**Comment by liach** [comment] 2019-01-18 05:37
Will have a discussion on whether to send new capacity or to send multiblock formation events and compute on client.

**Comment by liach** [comment] 2019-02-18 08:20
Partially resolved in #1723, forgot to put boiler fix in.

**Comment by liach** [comment] 2019-02-18 09:33
Finished in #1723 and #1730.

**Closed as completed by liach** 2019-02-18 09:33 UTC
Labels: bug, high priority, machines and structures
