### ISSUE TITLE
Blast furnace steel recipe broken

### ISSUE THREAD

**Issue by MtnDrew** [Railcraft/Railcraft#1630] opened 2019-01-08 23:45 UTC
So I have only a few tech mods installed that have ore generation and alloys in my entire modpack I put together for myself. Ender IO, Railcraft, and Forestry (Abyssalcraft as well if that counts although it's very different). Even though no other tech mods have an oredictionary Steel equivalent, Railcraft has disabled steel being able to be produced through a blast furnace, and has also disabled any ability to craft brass. Ender IO's alloy smelter does have the ability to make the steel (even though I'd really like the Blast furnace to still work and would even disable the alloy smelter from being able to do it if I could), but Ender IO cannot produce brass either. So that alloy is completely out. I've hunted through the config to see if there was any way I could re-enable these recipes through Railcraft, but haven't found anything. Is there any way to do this?

**To Reproduce**
Install Railcraft and Ender IO, and JEI.
Put iron and coal coke in the Blast Furnace.
Receive only slag.
Try to craft brass, look it up in JEI, realize it's not there.

**Expected behavior**
Be able to craft brass, since no mods I have installed have an equivalent.
Be able to re-enable steel production through the blast furnace in the config.

**Additional context**
Does not cause a crash, it's just not available and I am not able to find anything in the config to change that. I do have other mods installed such as Botania,  Thaumcraft, etc., if for some reason it could possibly be some extremely odd compatibility error and can  provide if needed, but absolutely no other steel adding/brass adding tech mods.

**Comment by Trinsdar** [comment] 2019-01-08 23:48
duplicate of #1623 and the other issue is already known

**Comment by MtnDrew** [comment] 2019-01-08 23:53
So it's not just with inventory tweaks, it's with any other mod? And will the issue with steel not being produceable through the blast furnace be added to that? I'm just wondering if there is something I'm missing. Edit: Oh, Inventory Tweaks. For some reason I was reading that as some form of craft tweaker. Well ignore the brass part then. Wouldn't want to lead you on a wild goose chase. Then let's just remove the brass part of this issue. Is there a way to re-enable steel production through the blast furnace? I'll check the ender io config and see if i can disable it's steel recipe, since it's kind of lame comparatively.

**Comment by Trinsdar** [comment] 2019-01-09 00:41
I think the steel issue was raised on the railcraft discord so they are already aware of it

**Comment by MtnDrew** [comment] 2019-01-09 00:50
Great! Thank you very much. I love this mod and the great features it has, so I usually try to make sure other mods features are disabled so they don't interfere with this one.

**Comment by liach** [comment] 2019-01-09 00:52
I will reopen this so developers don't forget about the steel thing.

**Comment by CovertJaguar** [comment] 2019-01-09 21:41
Fixed by https://github.com/Railcraft/Railcraft-API/commit/229464b4b9a8aee60912f9bc943544d4af5522c4

**Closed as completed by CovertJaguar** 2019-01-09 21:41 UTC
Labels: bug, high priority
