### ISSUE TITLE
Crash when trying to open the rock crusher GUI

### ISSUE THREAD

**Issue by LuigiHutch** [Railcraft/Railcraft#1589] opened 2018-12-25 22:39 UTC
**Description of the Bug**
Crash when trying to open the rock crusher GUI

**To Reproduce**
1. Build a Rock Crusher
2. Insert some items into it and power it
3. Try to open its GUI
4. Crash

**Expected behavior**
The GUI to open and it not to crash

**Screenshots & Video**
N/A

**Environment**
 - railcraft-12.0.0-beta-2.jar
 - forge-1.12.2-14.23.5.2796.jar 

**Additional context**
https://gist.github.com/LuigiHutch/32955d8ecbf3b24f0edae8559d4f29e3

**Comment by CovertJaguar** [comment] 2018-12-25 23:06
This is what happens when you have a deadline.

**Comment by liach** [comment] 2018-12-25 23:34
@CovertJaguar in your refactor, you should have kept the scale field instead of evaluating it. the scale was originally calculated on the server and sent to the client, but now you depend on the recipe which is only exist on the server side

**Comment by CovertJaguar** [comment] 2018-12-26 20:31
Ah, yep

**Comment by CovertJaguar** [comment] 2018-12-27 09:21
Actually... The problem is that it used to be based on a constant and now needs to be calculated because I added a time field to the recipes.

**Comment by liach** [comment] 2019-01-13 06:50
@CovertJaguar Does this still happen after moving to the new logic system? It no longer happens to me even before the move to logic, though the progress bar isn't being synchronized.

**Comment by CovertJaguar** [comment] 2019-01-13 10:50
It does not.

0c59a8bac9ecd5d8b7ad0bf2bd358bb1451bcc07

**Closed as completed by CovertJaguar** 2019-01-13 10:50 UTC
Labels: bug, high priority, machines and structures
