### ISSUE TITLE
[1.10.2] Tank Carts Contents not syncing

### ISSUE THREAD

**Issue by DatGurney** [Railcraft/Railcraft#1257] opened 2017-06-16 21:10 UTC
if a tank cart is filled up by a loader or bucket, the liquid doesnt render in the tank until the GUI is opened. Fluid still fills properly so its a fairly minor issue

**Comment by liach** [comment] 2017-06-16 21:41
Dupe of #1194

**Closed as completed by liach** 2017-06-16 21:41 UTC
Labels: duplicate
