### ISSUE TITLE
1.12 crash with IC2

### ISSUE THREAD

**Issue by Spenny519** [Railcraft/Railcraft#1407] opened 2018-05-17 22:02 UTC
![ic2crash](https://user-images.githubusercontent.com/36276355/40206042-4e39d8a0-59e3-11e8-821a-73c2327cec72.PNG)
and I don't get this crash when I just have ic2 and railcraft installed on the instance

**Comment by Spenny519** [comment] 2018-05-17 22:07
![modlist](https://user-images.githubusercontent.com/36276355/40206243-04aa8dd2-59e4-11e8-9a3d-c788ba766586.PNG)
This is the modlist I am using btw

**Comment by Chocohead** [comment] 2018-05-17 22:22
Looks like `detector` is empty, `battery` and `machine` are checked first.

**Comment by Spenny519** [comment] 2018-05-17 22:25
well the thing is that it was working with no crash yesterday and the this morning, without any changes to anything, it started crashing

**Comment by Spenny519** [comment] 2018-05-17 22:31
how do I fix it?

**Comment by liach** [comment] 2018-05-18 14:41
I do not know how this happens at all since the stack returned should be fine. Or should I register in regular recipes instead of ic2 crafting registry @Chocohead ?

**Comment by Spenny519** [comment] 2018-05-18 15:36
once I disabled the ic2 mod compatibility in the railcraft configs, I got it to load up without it crashing

**Comment by liach** [comment] 2018-05-18 15:47
I do not know what is wrong with the detectors. They are enabled in theory.

**Comment by Spenny519** [comment] 2018-05-18 16:00
oh btw @Chocohead do you have any plans on updating Advanced machines to 1.12 anytime soon?

**Comment by Chocohead** [comment] 2018-05-18 19:12
Changing to registering as a normal recipe won't fix the underlying issue that it couldn't find the detector, but without any concrete ability to reproduce the crash that's not especially possible. Have you disabled any particular Railcraft modules in the config that might have stopped it finding the detector?

As for Advanced Machines, it'll be ready when it's ready. It could do with more internal clean up, which by putting off in favour of more interesting projects has let it slip a little.

**Comment by Spenny519** [comment] 2018-05-18 20:24
Yes when i disabled the ic2 module in the railcraft config, it stopped crashing and now works

**Comment by Chocohead** [comment] 2018-05-18 20:34
But without disabling the IC2 module (ie having everything enabled) it does crash?

**Comment by Spenny519** [comment] 2018-05-18 20:40
Yes if i dont disable it, i crash

**Comment by Spenny519** [comment] 2018-05-18 20:41
But with the ic2 module disabled and everything else enabled, i dont crash

**Comment by Chocohead** [comment] 2018-05-20 00:28
Quite strange, it shouldn't be able to suddenly break itself without anything changing. We'll probably need additional logging to be able to narrow down on what's wrong, but given we can't directly give you a jar that does make the process more complicated. If I created a branch with some additional logging and protection around the IC2 module would you be ok with compiling and testing with it?

**Comment by Spenny519** [comment] 2018-05-20 02:43
Yeah im up to doing that to help out with it

**Comment by border999** [comment] 2018-05-20 03:20
this is a 1.12 version for Railcraft yes? Would there be any means by which I may procure this?

**Comment by Spenny519** [comment] 2018-05-20 04:11
@border999 it is an unofficial version with many bugs

**Comment by liach** [comment] 2018-05-20 04:12
@border999 Direct message to me on discord if you really want.

**Comment by Chocohead** [comment] 2018-05-20 14:19
That branch should have enough to get an idea why it isn't happy, unless it suddenly starts working again then we'll have no idea what ever went wrong.

**Comment by Spenny519** [comment] 2018-05-20 15:28
Okay when i get a chance i will compile it and test it out in a new instance with all the same mods

**Comment by liach** [comment] 2018-05-31 18:11
uh no, wrong issue. Should be #1136

**Comment by liach** [comment] 2018-06-30 05:09
Anyways I will close this one. When I ran ic2 with railcraft this never happened; no other users reported so.

**Closed as completed by liach** 2018-06-30 05:09 UTC
Labels: need more info, bug, medium priority, can't reproduce, mod compatibility, alpha

**Comment by gball19** [comment] 2019-05-31 21:35
If you use liteloader, the same issue is shown and seems to be repeatable.

**Comment by xJon** [comment] 2019-07-14 07:14
I can confirm this happens with LiteLoader and is fixed by using @asiekierka's [Extra Foam For LiteLoader](https://www.curseforge.com/minecraft/mc-mods/extra-foam-for-liteloader).
