### ISSUE TITLE
Outdated CoFH API

### ISSUE THREAD

**Issue by Nedelosk** [Railcraft/Railcraft#1292] opened 2017-07-27 22:01 UTC
The CoFH API of railcraft is outdated. The CoFH API of railcraft has the owner "CoFHAPI". But since the version 1.4 of the cofh api the name of the api owner is "cofhapi".
https://github.com/Railcraft/Railcraft/blob/mc-1.10.2/src/api/java/cofh/api/energy/package-info.java#L5
https://github.com/CoFH/CoFHLib/blob/1.10.2/src/main/java/cofh/api/energy/package-info.java#L5

**Comment by liach** [comment] 2017-07-27 23:19
Duplicate of #1203

**Closed as completed by liach** 2017-07-27 23:19 UTC
Labels: duplicate
