### ISSUE TITLE
Worldspike Ticking entity crash

### ISSUE THREAD

**Issue by MisterInsane** [Railcraft/Railcraft#1744] opened 2019-02-24 01:43 UTC
I have a worldspike placed in the Deep Dark from Extra Utilities 2. I created a mob grinder and chunkloaded it with a worldspike.

The server crashed a few hours ago with this log: https://pastebin.com/aRQQgQk9

We're running railcraft-12.0.0-beta-4.jar on forge 14.23.5.2808.

Any help would be appreciated.

**Comment by liach** [comment] 2019-02-24 05:04
Fixed in Railcraft 12.0.0 beta 5 already. Duplicate of #1594

**Closed as completed by liach** 2019-02-24 05:04 UTC
Labels: duplicate
