### ISSUE TITLE
1.10.2 Railcraft crashes on startup if the resources module is disabled

### ISSUE THREAD

**Issue by StardustAlpha** [Railcraft/Railcraft#1602] opened 2018-12-28 01:12 UTC
**Description of the Bug**
Railcraft causes Minecraft to crash when starting if the resources module is disabled.
Specifically, it crashes on the Mojang logo screen.
**To Reproduce**
1. Disable the Resources Module
2. Restart Minecraft

**Expected behavior**
The game reaches the title screen.

**Screenshots & Video**
[railcraft-problem.zip](https://github.com/Railcraft/Railcraft/files/2713678/railcraft-problem.zip)
Here is a zipped mp4 video of me reproducing the bug. Also, here is the crash log from the video in txt format.
[the-crash-log-from-the-video.txt](https://github.com/Railcraft/Railcraft/files/2713698/the-crash-log-from-the-video.txt)

**Environment**
 - Version
Not sure, but the mod jar is named Railcraft_1.10.2-10.4.1.jar.
 - Forge version
12.18.3.2511
 - Possible conflicting mods and their versions.
Minecraft Coder Pack 9.19, Forge Mod Loader 8.0.99.99, Minecraft Forge 12.18.3.2511, Minecraft 1.10.2

**Additional context**
I decided to isolate Railcraft and its dependencies when reporting this bug, since my usual pack is currently shown as having 42 mods.

**Comment by liach** [comment] 2018-12-28 01:17
Duplicate of #1532. You need to tweak worldspike config after disabling resources module for now, unfortunately.

**Closed as completed by liach** 2018-12-28 01:17 UTC
Labels: duplicate
