### ISSUE TITLE
Railcraft High Speed Tracks

### ISSUE THREAD

**Issue by edisonkendrick** [Railcraft/Railcraft#1316] opened 2017-08-14 01:29 UTC
Hi! I'm using railcraft 10.1.2 for 1.10.2. When I use the high speed tracks, they seem to be not able to **reach their top speed** and just maintains a _normal booster track speed (or even slower)_. I tried every form of redstone but there was no hint of speeding up. Is there any way to solve this? I've tried all of the versions.
(I have worldedit)

**Comment by liach** [comment] 2017-08-14 06:47
Duplicate of #1202

**Closed as completed by liach** 2017-08-14 06:47 UTC
Labels: duplicate
