### ISSUE TITLE
[TC-BETA6] [RC-10.3.1] Creosote Crash

### ISSUE THREAD

**Issue by Voxel-Friend** [Railcraft/Railcraft#1380] opened 2018-02-16 17:41 UTC
Installed Mods:
Thaumcraft BETA6
Railcraft 10.3.1

Launcher:
Twitch Client 

Crashlog: https://pastebin.com/cceVCGUT

Seems to be related to Creosote potion, perhaps Thaumcraft is looking for a recipe that isn't there.

**Comment by liach** [comment] 2018-02-16 17:55
interesting!

**Comment by MagusLucius** [comment] 2018-02-16 23:17
The problem is Thaumcraft attempting to cast the Creosote Potion to the Minecraft base type, I think.

"Caused by: java.lang.ClassCastException: mods.railcraft.common.items.potion.PotionTypeCreosote$$Lambda$537/1744195342 cannot be cast to net.minecraft.potion.PotionHelper$ItemPredicateInstance"

**Comment by liach** [comment] 2018-02-17 03:58
@Azanor You should not assume that all the conversions are concrete classes.

**Comment by liach** [comment] 2018-02-22 18:16
Closing since azanor already fixed it in his code.

**Closed as completed by liach** 2018-02-22 18:16 UTC
Labels: not railcraft, mod compatibility

**Comment by Voxel-Friend** [comment] 2018-02-24 03:04
Nice
