### ISSUE TITLE
Quarried Cobblestone into Quarried Stone instead of Quarried Block.

### ISSUE THREAD

**Issue by TCloudGaming** [Railcraft/Railcraft#1151] opened 2017-04-18 04:19 UTC
This is obviously a very small thing, but it would be nice if the Quarried Cobblestone would be smelted into Quarried Stone to make it more easily obtainable.

**Comment by CovertJaguar** [comment] 2017-04-18 13:56
@liach marking something as an open project is my prerogative, please stop. -.-

@Generalcamo I'll let you sort this out.

**Comment by Generalcamo** [comment] 2017-04-18 15:08
Duplicate of #1103

**Closed as completed by Generalcamo** 2017-04-18 15:08 UTC
Labels: duplicate, enhancement, good first issue, low priority
