### ISSUE TITLE
Tunnel bore drops when placed

### ISSUE THREAD

**Issue by josetodo** [Railcraft/Railcraft#1123] opened 2017-03-24 00:18 UTC
When i place the tunnel bore it don´t apear, well, it do the animation of placement but when is in the rail is like it was broken for a player and go as item to the floor. 

Thanks for all

**Comment by liach** [comment] 2017-03-24 04:37
This description is very confusing.

**Comment by dj3520** [comment] 2017-03-24 11:47
possibly google translate?

**Comment by josetodo** [comment] 2017-03-24 21:11
dont worry, solved thanks for all

**Comment by MrabEzreb** [comment] 2017-04-25 01:04
how did you solve this? I have the same issue, when I place the bore onto track, it immediately drops as an item.

**Comment by liach** [comment] 2017-04-25 01:16
Is there a big enough space? Try to use on creative singleplayer. Server modifications such as plugins may block the placement of tunnel bores since it is a well-known griefing tool.

**Comment by MrabEzreb** [comment] 2017-04-25 01:20
It worked in creative singleplayer, but it doesn't work on a (lan world) server. It doesn't have any plugins as it is just open to lan

**Comment by MrabEzreb** [comment] 2017-04-25 16:33
This only happens in the lan world, regardless of whether it is open to lan or not. The host and I both tested in a singleplayer world creative and survival, and it worked.

**Comment by liach** [comment] 2017-04-25 16:45
How about dedicated servers?

**Comment by liach** [comment] 2017-04-26 23:25
Why close?

**Comment by CovertJaguar** [comment] 2017-04-26 23:28
Because we have no idea how to replicate it and it seems that reporter can't either.

**Comment by liach** [comment] 2017-04-27 00:44
He said it is in lan world

**Comment by CovertJaguar** [comment] 2017-04-27 01:34
Oh, I must have misread it.

**Comment by liach** [comment] 2017-04-27 17:55
I tried in lan world and it worked correctly.

**Comment by liach** [comment] 2017-05-17 05:34
No one else is affected and we cannot reproduce it. Closing.

**Comment by Taketzu** [comment] 2017-05-18 22:37
I have the same problem in Multiplayer with my hosted Server. I don´t find a way to Fix it.

I have made a Video and a gif of the Problem but i can´t Upload it...
I Uploaded the Video on Youtube (Not Listed) https://youtu.be/F4Qoew6qHNA

Greetings Taketzu

**Comment by liach** [comment] 2017-05-18 23:46
@Taketzu Does this happen with only Railcraft, without other mods?

**Comment by Taketzu** [comment] 2017-05-19 00:00
If i use only Railcraft without other Mods, it works correctly.

**Comment by liach** [comment] 2017-05-19 02:12
Can you test and find out when does it happen? If you are using a modpack, can you report to the modpack author to help find out?

**Comment by Taketzu** [comment] 2017-05-19 06:10
Ok i will contact the FTB Team.

**Comment by 5t00** [comment] 2017-05-20 13:48
I've run into this as well - the tunnel bore pops off the rails and turns back into an object as soon as it gets placed in the world. This was with a dozen or so other mods running.

I've since pulled all the non-Railcraft mods out, and the issue persists - but with a new creative world, I can place the tunnel bore with no problem. 

The problem shows up for me in a SP world - would the save file for this world be helpful in diagnosing the problem? Would the list of mods be helpful, since the problem continues after they've been removed?

**Comment by liach** [comment] 2017-05-20 14:25
@5t00 The savegame would be very helpful.

**Comment by 5t00** [comment] 2017-05-20 14:40
Alright - does github have a handy place to upload something like this? Haven't gotten around to setting up a dropbox account yet or anything.


Also, just in case somebody has a different set of mods to help narrow down what's in common, here's what I was running when I ran into this:

Advanced Rocketry
AutoRegLib
Chameleon
compatlayer
Computronics
Deep Resonance
ElecCore
Embers
Immersive Engineering
Impractical Storage
IvToolkit
JEI
Journeymap
Just A Few Fish
Just Enough Buttons
LubVulpes
Mantle
mcjtylib
Minecolonies
OpenComputers
Psi
Quintessential Creatures
Railcraft
Recurrent Complex
RFTools
RFTools Control
Rustic
Storage Drawers
Tinker's Construct
Waila
WTF-Expedition
Vivecraft (so also Optifine)


I've also had a few other mods I've tried out and since removed, which may have done something:

Malisis Doors
Malisis Core
Roots
Ruins

So, a dozen-ish :p

**Comment by liach** [comment] 2017-05-20 16:02
@5t00 You can upload logs to https://gist.github.com and upload files with `selecting them` link in the `Write` box.

**Comment by 5t00** [comment] 2017-05-21 02:50
I haven't found any log files generated from this; there's no crash or error message that I've found. The save file should be available at https://www.dropbox.com/s/t3i8vcnid1q68o2/Tunnels.zip?dl=0 - this is the save that did have other mods on, has had them stripped out, and is still exhibiting the issue.

**Comment by liach** [comment] 2017-05-21 03:30
This map only needs Railcraft, right?

**Comment by 5t00** [comment] 2017-05-21 10:16
That's right - there's still directory artifacts from the other mods I had installed, but it should be back to Railcraft only.

**Comment by krokots** [comment] 2017-06-07 21:13
Hi, I have the same problem.
Minecraft 1.10.2, forge 12.18.3.2185
Railcraft 10.1.2
couple of other mods installed, I can provide list. 

Tunnel bore pops up immediately after placing in my survival save. But when I create a new creative world, I can place it and it won't pop up. 
Also, putting (in survival) bore on a track turn or track slope destroys the bore (in creative it won't let you to place there)

**Comment by krokots** [comment] 2017-06-11 12:22
Some additional info : creating a new survival world with cheats on. You can place bore then. So, at one point something happened in my old save, and since then I can't place bores.

Also : mod list: 
bdlib-1.12.4.24-mc1.10.2.jar
BiomesOPlenty-1.10.2-5.0.0.2236-universal.jar
CodeChickenLib-1.10.2-2.5.8.255-universal.jar
CoFHCore-1.10.2-4.1.1.156-universal.jar
EnderCore-1.10.2-0.4.1.65-beta.jar
EnderIO-1.10.2-3.1.183.jar
forestry_1.10.2-5.2.17.376.jar
gendustry-1.6.5.30-mc1.10.2.jar
ImmersiveEngineering-0.10-58.jar
ironchest-1.10.2-7.0.15.804.jar
jei_1.10.2-3.14.7.419.jar
morebees-1.10.2-1.3.2.jar
omlib-1.10.2-3.0.0-101.jar
ompd-1.10.2-3.0.0-22.jar
openmodularturrets-1.10.2-3.0.0-158.jar
OptiFine_1.10.2_HD_U_D8.jar
Railcraft_1.10.2-10.1.2.jar
SimpleOreScanner-1.0.0-1.10.2.jar
ThermalExpansion-1.10.2-5.0.4.90-universal.jar
ThermalFoundation-1.10.2-2.0.5.81-universal.jar

**Comment by Schmiggolas** [comment] 2017-06-12 17:08
Same problem here. I'm using the most recent FTB Direwolf20 Pack. As soon as the bore is placed it converts back to item form. 
// edit: running on ded. server btw.

**Comment by dacioromero** [comment] 2017-07-05 05:36
Got the same problem in FTB Beyond in survival, but not in a creative world.

EDIT: Must've been a problem with the save, it works everywhere else. Curious as to what happened.

**Comment by tonimark** [comment] 2018-01-18 17:31
I have the same issue! but I am not using a LAN or the multiplayer world, its single player at creative mod
with cheats mod for more information ask the mod pack that I use:https://forum.resonantri.se/
this log that appears when the bore gets placed and despawned:
[notes.txt](https://github.com/Railcraft/Railcraft/files/1643819/notes.txt)

and the video here:
(it takes me forever to upload and it won't)

**Comment by liach** [comment] 2018-01-18 19:51
@tonimark try and report the log again without foamfix.

**Comment by tonimark** [comment] 2018-01-19 20:46
k wait a few minutes to reinitializing the game and reproduce the issue

**Comment by liach** [comment] 2018-01-19 21:03
Remember to post the error log with full stacktrace

**Comment by tonimark** [comment] 2018-01-19 21:15
ok I see after removing foam fix the initializing gets very very slow

**Comment by tonimark** [comment] 2018-01-19 21:56
so I have a problem: the initializing freezes due too much ram almost allocated 7.5 GB from my 8 GB 
and still no results maybe foam fix request to reproduce the issue

**Comment by liach** [comment] 2018-01-20 01:44
Pinging @asiekierka for ideas.

**Comment by tonimark** [comment] 2018-01-20 15:05
I GOT WORSE NEWS not only bore won't be placed but every signe railcraft cart at any type of rail and i am using latest versions of railcraft

**Comment by asiekierka** [comment] 2018-01-20 15:24
>foamfix-0.7.0-beta2

There's your problem. You're using an ancient version of a mod which patches the everloving class out of Minecraft. http://unascribed.com/foamfix

>Resonant Rise

I'll give them a call.

(This only resolves @tonimark's issue; not the issue this was opened for, as the other reporters do not use an outdated version, or, in fact, any version of FoamFix.)

**Comment by liach** [comment] 2018-01-20 16:54
So @tonimark's discussion moves to #1370 now

**Comment by ryanlbowman** [comment] 2018-05-08 15:51
I am also having this problem. In a world I created a couple of weeks ago, when I tried to place a bore yesterday, it just drops.
I can create a new world, in survival (with cheats) or creative, and place one just fine, but not in the world I've been working on for a while. I crafted everything by hand, and it doesn't work. I've tried going into creative mode, opening to LAN (with and without cheats), going to a newly generated chunk, I've tried deleting the railcraft config files, updating to the latest version of railcraft (for 1.10.2) nothing works.

I've never played with railcraft before, and when I learned yesterday that it was in the modpack I was playing with, I wanted to give it a try, specifically the tunnel bore, so I was pretty disappointed when the first thing I tried to do with it is broken.  Is there anything else I can try to fix this for my existing world?

I'm playing the Stumped Village modpack for MC 1.10.2, from the curse launcher, with a few extra mods I've added and a bunch of config changes. But as I said, if I create a new world I can place one just fine.

**Comment by liach** [comment] 2018-05-08 16:39
can you play in that world and upload your latest log?

**Comment by ryanlbowman** [comment] 2018-05-08 16:47
Sure, this is the log from when I wiped the railcraft configs and restarted it this morning. All I did after restarting was try to place the tunnel bore, and then quit when it didn't work. If this isn't sufficient, I can play around for a while later tonight.
[latest.log](https://github.com/Railcraft/Railcraft/files/1984860/latest.log)

**Comment by liach** [comment] 2018-09-06 06:19
I will close this one because developers cannot replicate this issue, unfortunately.

**Comment by zacher29** [comment] 2019-05-12 22:31
Sorry to possibly reopen this topic. But i was able to recreate it after experiencing the issue. For some reason, for myself anyways, every time I generate a server for a new modpack including railcraft it causes an issue in chunk generation that prevents the borers from being placed down. Any servers generated after the first one no longer experience this problem. Once I also removed the chunks that had been generated and re-generated them this also fixed the problem. 

The culprit files are in the region folder, inside the world folder. I believe it may be an underlying issue with java or the OS that causes this to happen with the first server. Considering I never experienced this before hand and only AFTER I got a new PC. Im going to keep troubleshooting this in my spare time to see if I can get a fix in case anyone else is experiencing this rare problem.

**Comment by CountLagula** [comment] 2019-05-21 07:40
I also still have this problem. Running RailCraft 12.0.0 in a huge modpack on MP world, exactly as described. It works fine on the same modpack in creative-created singleplayer world. @liach Hopefully we can reopen as this is still an issue in RC12

**Comment by zacher29** [comment] 2019-05-21 18:42
I’ve been toying with this for the past couple days just seeing if I can get it narrowed down. I can’t seem to find what causes the error to happen. Although every first server for every new modpack it has this issue. If you wipe the region file that generates on world gen it just the entire world folder and relaunch, it solves the issue. I’m thinking it might be a Java issue but maybe not?

**Comment by dan96kid** [comment] 2019-05-26 00:42
I can also confirm that I'm having this issue.

**Comment by BluexRaven** [comment] 2019-06-03 21:47
Issue is happening to me on a custom modpack I've made and does not work on single player either
Server is showing an error message "No entity type is registered for class mods.railcraft.common.carts.EntityTunnelBorePart"
https://youtu.be/ymKdfyHANus
Video of what happens ingame

**Comment by JokerRH** [comment] 2019-06-08 18:58
Could this have something to do with the level seed? I can recreate it like this: Fresh install of Minecraft 1.12.2 with Forge 14.23.5.2779 and Railcraft 12.0.0, create a new world and use the seed "-5744720497347845794"
The issue still exists with Forge 14.23.5.2838.

**Comment by beatup667** [comment] 2019-06-15 02:53
Sorry if I’m interrupting a conversation or something like that but I am also having this problem. I was about to use it when I placed it it popped of the vanilla tracks. I am using the FTB ultimate (Reloaded) modpack and my goal was to make a train to all the spots I have/will make on the map. I’m very early game a spent about 2 hours getting the steel for the bore. Once I placed it it popped of the track I am going to see if game modes effects it or if tracks effect it for I have cheats enabled in case something breaks like this. I am currently loading new chunks to see if that effects it too. So as it seems different tracks don’t effect it and the new chunks didn’t either. I worked hard for the bore so this makes me sad. This was all on the same world (sp world) so far and I will see what will happen on a new one. On the creative world it worked fine. I just noticed I’m no longer connected to the internet on minecraft. Mabye that fixed it? Let me check. Nope. Mabye it’s worlds started in survival? Nope. Will opening my first world to lan help? Nope. I give up. It’s been an hour and it’s 11 pm I need some sleep.

**Comment by tnekohue** [comment] 2019-06-26 09:56
I am also having this issue on dedicated server, tunnel bore pops off the tracks when placed.

**Comment by Phanthalassa** [comment] 2019-06-26 16:53
Same problem here, dedicated mp server. Latest railcraft for 1.12.2 and forge 4836. Bores pop right back up when i place them on vanilla/electric track.

**Comment by DSH12** [comment] 2019-07-01 23:07
Same probleme. Dedicated mp server with forge-1.12.2-14.23.5.2838 and custom modpack (ic2, bc, thaumcraft6, forestry, iceandfire). Bore drops when placed on any track in Overworld, but works fine in nether(!). Also bore works fine on the same modpack in singleplayer world.

**Comment by Vectrobe** [comment] 2019-07-03 04:29
I'd hazard a guess this might be UUID related...

**Comment by DSH12** [comment] 2019-07-05 04:21
Okay, after some more test i can definitely say that the bore can drops in a single player too.
If this is UUID issue, any suggestions how can i fix this?

**Comment by Polosolo12** [comment] 2019-08-23 22:24
I would like to add I also have this issue. At first, I was certain I just didn't have enough space, but after a few minutes, I realize the bore cannot possibly be any larger because it would be impossible to place from a certain distance. After checking Youtube for usage, I realized something else may be a contributor.
I found this thread that accurately describes my issues. I am currently running Minecraft 1.12.2 with custom mods.
One thing that MAY be an issue is I added railcraft after already creating the world.... I read somewhere on this thread that may be the issue. I am going to see if I can get it to work in new chunks and if I can, hopefully this will be a temporary solution.

**Comment by Polosolo12** [comment] 2019-08-23 22:31
Good news! (ish) I went to a mystcraft age that I made after adding railcraft and the bore worked. If you are also experiencing this problem, try going to new areas in which chunks have not been loaded yet.

**Comment by CountLagula** [comment] 2019-08-23 22:38
@Polosolo12 your issue is a related, but slightly different issue. My issue occurred on a world which had railcraft installed for creation, and loading new chunks produces the same results, unfortunately.

**Comment by aking4125** [comment] 2020-01-26 03:16
I can also confirm this. The tunnel bore doesn't place in Multiplayer. Running a dedicated server with Foamfix 0.10.10 for 1.12.2 and when placing the bore, it just drops as an item. All other carts are working though so for us it's just the bore atm.

**Comment by marewey** [comment] 2020-02-17 18:05
I am also having this issue, any sign of a fix any time soon?

**Comment by Skywrath-Mage** [comment] 2020-02-18 16:19
Hello, 
i have the same issue with my sporge server. 
if you want i can give you access for investigating and discover whats the issue exactly.

**Comment by zarte13** [comment] 2020-04-27 04:21
Doesn't work for me too. I tried checking for the logs and enabling debugs in the railcraft config but nothing. It disappears on placement. 

I tried removing foamfix, doesn't work either. 
I even tried disabling collision in the config but nothing works. 
Tried different track types also.
![2020-04-26-20-50-47 (1)](https://user-images.githubusercontent.com/34402486/80333739-153d7600-881d-11ea-9182-f5cc27c66ae6.gif)




Finally, I tried it in singleplayer and it can be placed fine but when I try to place it on any multiplayer server it doesn't work.

**Comment by liach** [comment] 2020-04-27 04:30
Is there anything in server log?

**Comment by zarte13** [comment] 2020-04-27 14:48
> Is there anything in server log?

No... absolutely nothing
client logs and server logs nothing
Something interesting: a world generated by a server and loaded in singleplayer: can't place the tunnel bore
a world generated in singleplayer but loaded by a server: can place tunnel bore..
seem to be related to the world folder.

**Comment by blackstormlab** [comment] 2020-04-30 19:04
still happening to this day

**Comment by PeaceDealer** [comment] 2021-02-22 22:27
Hey, just chipping in. Experiencing this issue on a FTB Resonant Rise modpack, on the server.
Works fine in single player.

Not seeing any entries in the server logs

**Comment by changemenemo** [comment] 2021-05-06 17:19
I can confirm that it's still happening to this day:
other people are confirming it with the last version I guess as those ones which are duplicates:
https://github.com/Railcraft/Railcraft/issues/2010
https://github.com/Railcraft/Railcraft/issues/1999
https://github.com/Railcraft/Railcraft/issues/1924
https://github.com/Railcraft/Railcraft/issues/1913

For my setup, it has definitely something to do with the Seed.
It does happen with the same seed and same mods in multiplayer and single player.
nothing in the server logs that I can see, or maybe there is the possibility to activate more verbosing in the logs ?

This is the complete list of the mods and version that I took from one of my crash logs when it occasionally happens:

> 	| LCHIJA  | minecraft                         | 1.12.2            | minecraft.jar                                  | None                                     |
> 	| LCHIJA  | mcp                               | 9.42              | minecraft.jar                                  | None                                     |
> 	| LCHIJA  | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCHIJAE | forge                             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
> 	| LCHIJA  | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
> 	| LCHIJA  | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                         | None                                     |
> 	| LCHIJA  | bdlib                             | 1.14.3.12         | bdlib-1.14.3.12-mc1.12.2.jar                   | None                                     |
> 	| LCHIJA  | buildcraftlib                     | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | buildcraftcore                    | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | buildcraftbuilders                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | buildcrafttransport               | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | buildcraftsilicon                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | buildcraftenergy                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | ic2                               | 2.8.221-ex112     | industrialcraft-2-2.8.221-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
> 	| LCHIJA  | jei                               | 4.15.0.293        | jei_1.12.2-4.15.0.293.jar                      | None                                     |
> 	| LCHIJA  | forestry                          | 5.8.2.422         | forestry_1.12.2-5.8.2.422.jar                  | None                                     |
> 	| LCHIJA  | buildcraftcompat                  | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | buildcraftfactory                 | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | buildcraftrobotics                | 7.99.24.8         | buildcraft-all-7.99.24.8.jar                   | None                                     |
> 	| LCHIJA  | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2-3.2.3.358-universal.jar  | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
> 	| LCHIJA  | redstoneflux                      | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
> 	| LCHIJA  | cofhcore                          | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
> 	| LCHIJA  | cofhworld                         | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
> 	| LCHIJA  | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                       | None                                     |
> 	| LCHIJA  | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                    | None                                     |
> 	| LCHIJA  | thaumcraft                        | 6.1.BETA26        | Thaumcraft-1.12.2-6.1.BETA26.jar               | None                                     |
> 	| LCHIJA  | thermalfoundation                 | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
> 	| LCHIJA  | thermalexpansion                  | 5.5.7             | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
> 	| LCHIJA  | enderio                           | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | enderiointegrationtic             | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | tconstruct                        | 1.12.2-2.13.0.179 | TConstruct-1.12.2-2.13.0.179.jar               | None                                     |
> 	| LCHIJA  | conarm                            | 1.2.5.10          | conarm-1.12.2-1.2.5.10.jar                     | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
> 	| LCHIJA  | enderiobase                       | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | enderioconduits                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | enderioconduitsappliedenergistics | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | enderioconduitsopencomputers      | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | refinedstorage                    | 1.6.16            | refinedstorage-1.6.16.jar                      | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
> 	| LCHIJA  | enderioconduitsrefinedstorage     | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | enderiointegrationforestry        | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | enderiointegrationticlate         | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | enderioinvpanel                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | ftblib                            | 5.4.7.2           | FTBLib-5.4.7.2.jar                             | None                                     |
> 	| LCHIJA  | enderiomachines                   | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | enderiopowertools                 | 5.2.66            | EnderIO-1.12.2-5.2.66.jar                      | None                                     |
> 	| LCHIJA  | energyconverters                  | 1.3.7.30          | energyconverters_1.12.2-1.3.7.30.jar           | None                                     |
> 	| LCHIJA  | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9(1).jar                  | None                                     |
> 	| LCHIJA  | ftbutilities                      | 5.4.1.131         | FTBUtilities-5.4.1.131.jar                     | None                                     |
> 	| LCHIJA  | advgenerators                     | 0.9.20.12         | generators-0.9.20.12-mc1.12.2.jar              | None                                     |
> 	| LCHIJA  | gravestone                        | 1.3.1             | GraveStone-1.12.2-Graves-1.3.1.jar             | None                                     |
> 	| LCHIJA  | gravestone-extended               | 1.3.5.1           | GraveStone-1.12.2-Extended-1.3.5.1.jar         | None                                     |
> 	| LCHIJA  | hammercore                        | 2.0.6.26          | HammerLib-1.12.2-2.0.6.26.jar                  | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
> 	| LCHIJA  | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
> 	| LCHIJA  | journeymap                        | 1.12.2-5.7.1      | journeymap-1.12.2-5.7.1.jar                    | None                                     |
> 	| LCHIJA  | modnametooltip                    | 1.10.1            | modnametooltip_1.12.2-1.10.1.jar               | None                                     |
> 	| LCHIJA  | railcraft                         | 12.0.0-rc-1       | railcraft-12.0.0-rc-1.jar                      | a0c255ac501b2749537d5824bb0f0588bf0320fa |
> 	| LCHIJA  | simplequarry                      | 12.3.28           | SimpleQuarry-1.12.2-12.3.28.jar                | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
> 	| LCHIJA  | thaumicjei                        | 1.6.0             | ThaumicJEI-1.12.2-1.6.0-27.jar                 | None                                     |
> 	| LCHIJA  | thermaldynamics                   | 2.5.6             | ThermalDynamics-1.12.2-2.5.6.1-universal.jar   | None    


The seed is `CubeCodersPowered` and as you can imagine the server and world has been generated through AMP from CubeCoders https://cubecoders.com/ but this is just as a remark since it has nothing to do with them since it happens also with a different seed.
So I guess it's multifactorial: The seed is involved but probably also forge and maybe the interaction with another mod. 

I can't test the last version of railcraft since it crashed on my server. 


EDIT:
To add some matter to the problem, there are a lot of reddit threads about this problem and they 're all talk talking about the seed.
The seed in my case is : -447167 
I tried to change it on the server by stopping, change the value, restart but no success yet

**Comment by changemenemo** [comment] 2021-05-11 02:18
@liach hi,

I know this mod is not actively developed anymore because of the drama of 2019 and all that, since I don't get any answers even on the patreon community page. But would it be irrealistic to ask if you have the time to actually try to reproduce this bug with me and see if the answer resides in railcraft or something else?

**Comment by Twisted-Code** [comment] 2021-05-12 15:00
@boistordu 
> nothing in the server logs that I can see, or maybe there is the possibility to activate more verbosing in the logs ?

That might help if it exists, but it probably doesn't, unfortunately... one reason I was so open to running one of @maxanier's test versions of Vampirism a while back for my server. I know the power of aggressive logging :-). Maybe one of the devs can do the same here: add some Logger statements around the relevant code and share the test build here?
> But would it be irrealistic to ask if you have the time to actually try to reproduce this bug with me and see if the answer resides in railcraft or something else?

Pardon me if I come off as rude, but I don't think that'll help much (due to the absence of most of the debugging tools that allow for scientific discovery of the root problem. Not that it isn't a nice idea if it would work). It's not that they don't believe you and need you to "demonstrate" the bug. It's that something else, possibly another mod, is needed for it to happen, but no one knows what it is. since no one knows what it is, the developers don't know that they need to put it in their development environment, and thus don't see the interaction when they make a test build.
try asking yourself "what is the common thread among all these reports I'm seeing?" Is one mod in common with all of them? See if that mod causes it to happen in a fresh install with just that mod and Railcraft. The smaller the set of mods that causes the issue, the better.

See also: [How to Report Bugs Effectively](https://web.archive.org/web/20200118103956/https://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

edit: shit, why did I decide to actually ping Maxanier when a silent mention might've done? Welp, damage done now... Sorry for any inconvenience Max

**Comment by BraedonLeonard** [comment] 2021-09-02 21:27
If the fix for this isn't in your world, a simple fix is to go to the coordinates (0,0,0) in your world and get rid of all lava in the area (or if there isn't lava, maybe just get rid of all the blocks in the area). That should fix it.

**Comment by maleksware** [comment] 2021-09-11 06:59
Fixed in #2024 .

**Closed as completed** 2022-06-01 04:25 UTC
Labels: need more info, needs verification, medium priority, carts
