### ISSUE TITLE
Slopes, Curves, Junctions

### ISSUE THREAD

**Issue by kylesy20** [Railcraft/Railcraft#987] opened 2016-11-01 16:57 UTC
Just a suggestion. Is it possible to add smoother slopes; smoother curves; and smoother junctions. (Similar to that of Traincraft)

**Comment by liach** [comment] 2016-11-01 17:55
Not really, cuz it will be more than one block, and it breaks mechanics.

**Comment by CovertJaguar** [comment] 2016-11-01 22:05
Duplicate of #787

**Closed as completed by CovertJaguar** 2016-11-01 22:05 UTC
Labels: duplicate
