### ISSUE TITLE
Having a hard time pushing carts with the player

### ISSUE THREAD

**Issue by MalkContent** [Railcraft/Railcraft#1003] opened 2016-11-09 10:25 UTC
As title says, having a hard time pushing carts with the players body. I can however shove carts just fine with the crowbars.
I don't understand the way pushing works completely, but it does seem buggy:

1. can't push freshly placed cart at all, but shove with crowbar
2. can push cart in the direction opposite to it's previous moving direction, but this ability diminishes 
3. after grinding to halt in 2., can now push in the other direction like with 2.

Maybe it's something like speed getting added in the wrong direction, idk. I only have the faintest idea, really. Hell, maybe it's the ghostly halloween carts being ghostly.

rc 10.0.0.0 (with ghostly halloween carts)
forge x2122

**Comment by Ristellise** [comment] 2016-11-09 11:07
seems like a old bug from 1.7... i had those issues too.

**Comment by liach** [comment] 2016-11-10 21:57
@MalkContent I thought this is intended behavior. In vanilla, you also cannot push minecarts -- you go through them; in Railcraft, however, minecarts have collision boxes and can collide with players but not pushed. As you say, use a crowbar.

**Comment by MalkContent** [comment] 2016-11-10 23:47
You can push minecarts in vanilla. You can go through them, but you will still push them, like with other mobs, really, and the pushing is quite an effective way of moving them, moreso than sitting in one and pressing forward.  
Also you /can/ push rc minecarts, but they got some weird behaviour. I also had a weird thing with a small cart train of 3 carts, with creepers inside the carts (i was testing stuff and it came up). That one would eratically change direction and it might be related to this issue.

**Comment by liach** [comment] 2016-11-10 23:50
How is the behavior weird? For the creeper one, it is probably related to #316.

**Comment by MalkContent** [comment] 2016-11-11 08:25
You can push rc minecarts in the direction opposite to which they previously moved, but it get's increasingly less effective. once you can't push anymore, you can push in the original direction.
See opening post, I guess.
And I think the creeper issue might be related due to the change in direction. That's just a guess though, and might as well not be the case.

**Comment by CovertJaguar** [comment] 2016-11-12 22:19
You can't have both collision boxes and pushing or at least I never figured it out.

**Comment by MalkContent** [comment] 2016-11-12 23:44
kay :) i have no issue with that other than this could go into a readme or something

**Comment by liach** [comment] 2017-03-03 20:58
Since this is really nothing, I will close this.

**Closed as completed by liach** 2017-03-03 20:58 UTC
Labels: working as intended, not a bug, carts
