### ISSUE TITLE
[1.12.2][Crash] "Ticking block entity" when placing boilers

### ISSUE THREAD

**Issue by ProxyPlayerHD** [Railcraft/Railcraft#1605] opened 2018-12-29 03:41 UTC
**Description of the Bug**
When i placed some (solid fuel) boilers the game just crashed, the world is completely broken as any attempt at opening it just instantly crash the game again

**Logs & Environment**

[LOG](https://pastebin.com/w9ybfVbm)

**Comment by liach** [comment] 2018-12-29 08:05
duplicate of #1583

**Closed as completed by liach** 2018-12-29 08:05 UTC
Labels: duplicate

**Comment by ProxyPlayerHD** [comment] 2018-12-29 09:22
oops sorry. i searched for ticking block entity and didn't find anything

**Comment by liach** [comment] 2018-12-29 17:30
No worries, I do expect people to report duplicate major bugs.

**Comment by ProxyPlayerHD** [comment] 2018-12-29 22:44
that's how you know they are major. :)

**Comment by CovertJaguar** [comment] 2018-12-29 23:40
I'm slowly working my way through the MBS bugs.
