### ISSUE TITLE
Crash randomly

### ISSUE THREAD

**Issue by jonharn** [Railcraft/Railcraft#1562] opened 2018-12-10 19:47 UTC
[crash-2018-12-10_14.45.16-server.txt](https://github.com/Railcraft/Railcraft/files/2664687/crash-2018-12-10_14.45.16-server.txt)

**Comment by liach** [comment] 2018-12-10 19:50
"count number of running locomotive" regression.

**Comment by CovertJaguar** [comment] 2018-12-11 03:20
Duplicate of #1557 

The crashes might be different, but the cause is the same.

**Closed as completed by CovertJaguar** 2018-12-11 03:20 UTC
Labels: duplicate, bug, high priority, carts
