### ISSUE TITLE
[1.10.2] Server Crash with Undercutter Cart

### ISSUE THREAD

**Issue by Prodiod** [Railcraft/Railcraft#1020] opened 2016-11-21 04:46 UTC
A player of mine put some stone in an undercutter cart, and it crashed the server. 

[crash-2016-11-20_20.28.39-server.txt](https://github.com/CovertJaguar/Railcraft/files/602744/crash-2016-11-20_20.28.39-server.txt)

**Comment by liach** [comment] 2016-11-22 04:36
Duplicate of #988

**Closed as completed** 2016-11-23 09:18 UTC
Labels: duplicate
