### ISSUE TITLE
TNT and TNT minecar exploding in one or two blocks of track with track kit installed will crash the game

### ISSUE THREAD

**Issue by CharlyC2018** [Railcraft/Railcraft#2023] opened 2021-08-22 16:38 UTC
In the figure below, detonating 1 does not crash the game, but 2 does
![image](https://user-images.githubusercontent.com/26193608/130362975-2012ba8a-15d1-4661-8428-4f3ab68335d2.png)

**Comment by CharlyC2018** [comment] 2021-08-22 16:43
rc版本是12.0.0

**Comment by maleksware** [comment] 2021-08-22 17:35
Please attach crash logs for developers to understand the situation.

**Comment by CharlyC2018** [comment] 2021-08-24 13:37
[2021-08-22-3.log](https://github.com/Railcraft/Railcraft/files/7039543/2021-08-22-3.log)

**Comment by maleksware** [comment] 2021-08-26 06:10
Here's the error:

[23:47:03] [Client thread/ERROR] [railcraft]: Invalid list entry while Blacklisting Cargo: ic2:.*bat((pack)|(tery))
[23:47:03] [Client thread/ERROR] [railcraft]: java.lang.IllegalArgumentException: Invalid Item while parsing config line: ic2:.*bat((pack)|(tery))
[23:47:03] [Client thread/ERROR] [railcraft]: Invalid list entry while Blacklisting Cargo: ic2:.*_crystal
[23:47:03] [Client thread/ERROR] [railcraft]: java.lang.IllegalArgumentException: Invalid Item while parsing config line: ic2:.*_crystal
[23:47:03] [Client thread/ERROR] [railcraft]: Invalid list entry while Blacklisting Cargo: ic2:jetpack_electric
[23:47:03] [Client thread/ERROR] [railcraft]: java.lang.IllegalArgumentException: Invalid Item while parsing config line: ic2:jetpack_electric
[23:47:03] [Client thread/ERROR] [railcraft]: Invalid list entry while Blacklisting Cargo: ic2:energy_pack
[23:47:03] [Client thread/ERROR] [railcraft]: java.lang.IllegalArgumentException: Invalid Item while parsing config line: ic2:energy_pack
[23:47:03] [Client thread/ERROR] [railcraft]: Invalid list entry while Blacklisting Cargo: ic2:lappack
[23:47:03] [Client thread/ERROR] [railcraft]: java.lang.IllegalArgumentException: Invalid Item while parsing config line: ic2:lappack
[23:47:03] [Client thread/ERROR] [railcraft]: Invalid list entry while Blacklisting Cargo: ic2:te#68-75
[23:47:03] [Client thread/ERROR] [railcraft]: java.lang.IllegalArgumentException: Invalid Item while parsing config line: ic2:te#68-75

**Comment by maleksware** [comment] 2021-08-26 14:15
Do you have any other mods installed? seems like IC2 is involved

**Comment by CharlyC2018** [comment] 2021-08-26 14:50
Mod list
I still crash like this when I add IC2
![image](https://user-images.githubusercontent.com/26193608/130984624-5de71e73-ce7b-4fa0-863b-7f8b468e1642.png)

---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2021-08-26 22:43:30 CST
Description: Unexpected error

java.lang.NullPointerException
    at org.dimdev.vanillafix.crashes.ProblemToast.getModCause(ProblemToast.java:41)
    at org.dimdev.vanillafix.crashes.ProblemToast.draw(ProblemToast.java:30)
    at net.minecraft.client.gui.toasts.GuiToast$ToastInstance.render(SourceFile:115)
    at net.minecraft.client.gui.toasts.GuiToast.drawToast(SourceFile:35)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1121)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['Charly_C'/127, l='MpServer', x=-1233.18, y=4.00, z=263.75]]
  Chunk stats: MultiplayerChunkCache: 265, 265
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-1270,4,214), Chunk: (at 10,0,6 in -80,13; contains blocks -1280,0,208 to -1265,255,223), Region: (-3,0; contains chunks -96,0 to -65,31, blocks -1536,0,0 to -1025,255,511)
  Level time: 151011 game time, 42296 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 52 total; [EntityItem['item.tile.dirt.default'/257, l='MpServer', x=-1229.80, y=3.54, z=269.16], EntityItem['item.tile.dirt.default'/258, l='MpServer', x=-1232.60, y=2.50, z=268.43], EntityItem['item.tile.dirt.default'/259, l='MpServer', x=-1229.38, y=3.63, z=268.64], EntityItem['item.tile.dirt.default'/260, l='MpServer', x=-1230.69, y=3.69, z=268.55], EntityItem['item.item.railcraft.track_kit.railcraft_buffer'/261, l='MpServer', x=-1232.35, y=4.74, z=268.71], EntityItem['item.tile.railcraft.track.flex.abandoned'/262, l='MpServer', x=-1231.48, y=4.43, z=268.54], EntityItem['item.tile.railcraft.track.flex.abandoned'/263, l='MpServer', x=-1232.64, y=4.79, z=268.55], EntityItem['item.tile.dirt.default'/264, l='MpServer', x=-1229.43, y=2.66, z=267.29], EntityItem['item.tile.dirt.default'/265, l='MpServer', x=-1232.37, y=2.71, z=267.39], EntityItem['item.tile.dirt.default'/266, l='MpServer', x=-1233.47, y=3.45, z=267.48], EntityItem['item.tile.dirt.default'/267, l='MpServer', x=-1229.30, y=3.45, z=267.42], EntityItem['item.tile.dirt.default'/268, l='MpServer', x=-1233.59, y=2.75, z=266.71], EntitySheep['羊'/148, l='MpServer', x=-1293.37, y=4.00, z=192.33], EntityPig['猪'/151, l='MpServer', x=-1292.18, y=4.00, z=236.71], EntityItemFrame['物品展示框'/154, l='MpServer', x=-1255.50, y=5.50, z=216.03], EntityItemFrame['物品展示框'/155, l='MpServer', x=-1253.50, y=5.50, z=216.03], EntityItemFrame['物品展示框'/156, l='MpServer', x=-1257.50, y=5.50, z=216.03], EntityItemFrame['物品展示框'/157, l='MpServer', x=-1250.50, y=5.50, z=214.03], EntityItemFrame['物品展示框'/159, l='MpServer', x=-1240.50, y=5.50, z=214.03], EntityItemFrame['物品展示框'/160, l='MpServer', x=-1240.50, y=5.50, z=220.97], EntityItemFrame['物品展示框'/161, l='MpServer', x=-1238.50, y=5.50, z=214.03], EntityItemFrame['物品展示框'/162, l='MpServer', x=-1236.50, y=5.50, z=214.03], EntityItemFrame['物品展示框'/163, l='MpServer', x=-1234.50, y=5.50, z=214.03], EntityItemFrame['物品展示框'/164, l='MpServer', x=-1234.50, y=5.50, z=217.97], EntityItemFrame['物品展示框'/165, l='MpServer', x=-1232.50, y=5.50, z=215.03], EntityItemFrame['物品展示框'/166, l='MpServer', x=-1232.50, y=5.50, z=220.97], EntitySheep['羊'/167, l='MpServer', x=-1282.80, y=4.00, z=285.30], EntitySheep['羊'/168, l='MpServer', x=-1283.21, y=4.00, z=272.76], EntitySheep['羊'/169, l='MpServer', x=-1202.22, y=4.00, z=191.20], EntityItemFrame['物品展示框'/170, l='MpServer', x=-1230.50, y=5.50, z=217.97], EntityItemFrame['物品展示框'/171, l='MpServer', x=-1230.50, y=5.50, z=215.03], EntityItemFrame['物品展示框'/172, l='MpServer', x=-1228.50, y=5.50, z=220.97], EntityItemFrame['物品展示框'/173, l='MpServer', x=-1228.50, y=5.50, z=208.03], EntityItemFrame['物品展示框'/174, l='MpServer', x=-1226.50, y=5.50, z=214.03], EntityItemFrame['物品展示框'/175, l='MpServer', x=-1226.50, y=5.50, z=217.97], EntityItemFrame['物品展示框'/176, l='MpServer', x=-1224.50, y=5.50, z=215.03], EntityItemFrame['物品展示框'/177, l='MpServer', x=-1224.50, y=5.50, z=217.97], EntityItemFrame['物品展示框'/178, l='MpServer', x=-1222.50, y=5.50, z=214.03], EntityItemFrame['物品展示框'/179, l='MpServer', x=-1220.50, y=5.50, z=212.03], EntityItemFrame['物品展示框'/180, l='MpServer', x=-1218.50, y=5.50, z=214.03], EntityChicken['鸡'/181, l='MpServer', x=-1278.11, y=4.00, z=264.22], EntityItemFrame['物品展示框'/182, l='MpServer', x=-1257.50, y=5.50, z=240.03], EntityItemFrame['物品展示框'/183, l='MpServer', x=-1255.50, y=5.50, z=240.03], EntityItemFrame['物品展示框'/184, l='MpServer', x=-1253.50, y=5.50, z=240.03], EntityItemFrame['物品展示框'/185, l='MpServer', x=-1215.03, y=5.50, z=216.50], EntityChicken['鸡'/186, l='MpServer', x=-1265.89, y=4.00, z=289.27], EntityPlayerSP['Charly_C'/127, l='MpServer', x=-1233.18, y=4.00, z=263.75], EntityCartTNT['TNT车'/249, l='MpServer', x=-1231.50, y=4.06, z=268.50], EntityItem['item.tile.dirt.default'/251, l='MpServer', x=-1231.73, y=1.46, z=270.27], EntityItem['item.tile.dirt.default'/252, l='MpServer', x=-1232.66, y=2.90, z=270.55], EntityItem['item.tile.dirt.default'/253, l='MpServer', x=-1231.28, y=1.77, z=268.19], EntityItem['item.tile.dirt.default'/255, l='MpServer', x=-1232.43, y=3.76, z=269.32]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_251, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 753944912 bytes (719 MB) / 1241513984 bytes (1184 MB) up to 8589934592 bytes (8192 MB)
  JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 27 mods loaded, 27 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                    | Version        | Source                                             | Signature                                |
       |:------ |:--------------------- |:-------------- |:-------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2         | minecraft.jar                                      | None                                     |
       | LCHIJA | mcp                   | 9.42           | minecraft.jar                                      | None                                     |
       | LCHIJA | FML                   | 8.0.99.99      | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                 | 14.23.5.2855   | forge-1.12.2-14.23.5.2855.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forceasciifont        | 1.0.0          | ForceAsciiFont.class                               | None                                     |
       | LCHIJA | jecharacters          | 1.12.0-3.5.0   | JustEnoughCharacters-1.12.0-3.5.0【JEI-通用拼音搜索】.jar  | None                                     |
       | LCHIJA | foamfixcore           | 7.7.4          | minecraft.jar                                      | None                                     |
       | LCHIJA | buildcraftlib         | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | buildcraftcore        | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | buildcraftbuilders    | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | buildcrafttransport   | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | buildcraftsilicon     | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | ic2                   | 2.8.221-ex112  | industrialcraft-2-2.8.221-ex112【工业2】.jar           | de041f9f6187debbc77034a344134053277aa3b0 |
       | LCHIJA | buildcraftcompat      | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | buildcraftenergy      | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | buildcraftfactory     | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | buildcraftrobotics    | 7.99.24.8      | buildcraft-all-7.99.24.8【建筑】.jar                   | None                                     |
       | LCHIJA | findme                | 1.1.0          | findme-1.12.2-1.1.0-8【找我】.jar                      | None                                     |
       | LCHIJA | foamfix               | 0.10.14-1.12.2 | foamfix-0.10.14-1.12.2【泡沫修复】.jar                   | None                                     |
       | LCHIJA | waila                 | 1.8.26         | Hwyla-1.8.26-B41_1.12.2【这是你正在看的东西】.jar             | None                                     |
       | LCHIJA | jei                   | 4.16.1.302     | jei_1.12.2-4.16.1.302【JEI】.jar                     | None                                     |
       | LCHIJA | railcraft             | 12.0.0         | railcraft-12.0.0【铁路】.jar                           | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LCHIJA | resourcepackorganizer | 1.0.4          | ResourcePackOrganizer++MC-1.12++v1.0.4【材质包管理器】.jar | None                                     |
       | LCHIJA | surge                 | 2.0.79         | Surge-1.12.2-2.0.79【潮涌】.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | torchmaster           | 1.8.4.84       | torchmaster_1.12.2-1.8.4.84【火炬大师】.jar              | 5e9a436b366831c8f54a7e80b015784da69278c6 |
       | LCHIJA | vanillafix            | 1.0.10-150     | VanillaFix-1.0.10-150【香草修复】.jar                    | None                                     |
       | LCHIJA | wawla                 | 2.6.275        | Wawla-1.12.2-2.6.275【高亮信息显示】.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
  Loaded coremods (and transformers): ForceAsciiFont (ForceAsciiFont-1.0.0【强制ASCII字体】.jar)
                                        io.github.zekerzhayard.forceasciifont.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150【香草修复】.jar)
                                        
                                      JechCore (JustEnoughCharacters-1.12.0-3.5.0【JEI-通用拼音搜索】.jar)
                                        me.towdium.jecharacters.core.JechClassTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.79【潮涌】.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.14-1.12.2【泡沫修复】.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 465.89' Renderer: 'NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2'
  Suspected Mods: java.lang.RuntimeException: java.io.IOException: 文件名、目录名或卷标语法不正确。
                      at org.dimdev.utils.ModIdentifier.makeModMap(ModIdentifier.java:74)
                      at org.dimdev.utils.ModIdentifier.identifyFromStacktrace(ModIdentifier.java:21)
                      at net.minecraft.crash.CrashReport.md32ace0$lambda$afterPopulateEnvironment$0$0(CrashReport.java:547)
                      at net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96)
                      at net.minecraft.crash.CrashReport.handler$zbd000$afterPopulateEnvironment(CrashReport.java:545)
                      at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:144)
                      at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
                      at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3952)
                      at net.minecraft.client.main.Main.main(SourceFile:123)
                      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                      at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
                      at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
                      at java.lang.reflect.Method.invoke(Unknown Source)
                      at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
                      at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
                  Caused by: java.io.IOException: 文件名、目录名或卷标语法不正确。
                      at java.io.WinNTFileSystem.canonicalize0(Native Method)
                      at java.io.WinNTFileSystem.canonicalize(Unknown Source)
                      at java.io.File.getCanonicalPath(Unknown Source)
                      at java.io.File.getCanonicalFile(Unknown Source)
                      at org.dimdev.utils.ModIdentifier.makeModMap(ModIdentifier.java:72)
                      ... 14 more
  Launched Version: HMCL 3.3.188
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 465.89, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: 简体中文 (中国)
  Profiler Position: N/A (disabled)
  CPU: 16x AMD Ryzen 7 3700X 8-Core Processor
  Client Crashes Since Restart: 2
  Integrated Server Crashes Since Restart: 0

**Comment by liach** [comment] 2021-09-02 23:13
Try without vanillafix. Seems a bug in vanillafix is eating the original stack trace of the bug.

**Comment by CovertJaguar** [comment] 2022-06-01 01:00
Cannot reproduce and no proper log provided. Closing.

**Closed as completed by CovertJaguar** 2022-06-01 01:00 UTC
Labels: needs verification, can't reproduce
