### ISSUE TITLE
Railcraft 1.12.2 Bug

### ISSUE THREAD

**Issue by NorbertVipPl** [Railcraft/Railcraft#1851] opened 2019-06-17 12:11 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 6/17/19 1:45 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Railcraft (railcraft)
Caused by: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: mods.railcraft.common.items.ItemFilterBeeGenome.<init>()void/newInvokeSpecial
	at mods.railcraft.common.items.RailcraftItems.<clinit>(RailcraftItems.java:125)
	at mods.railcraft.common.core.RailcraftConfig.loadItems(RailcraftConfig.java:563)
	at mods.railcraft.common.core.RailcraftConfig.preInit(RailcraftConfig.java:167)
	at mods.railcraft.common.core.Railcraft.preInit(Railcraft.java:149)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalAccessError: no such constructor: mods.railcraft.common.items.ItemFilterBeeGenome.<init>()void/newInvokeSpecial
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483)
	... 39 more
Caused by: java.lang.NoClassDefFoundError: forestry/api/apiculture/EnumBeeChromosome
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
	... 39 more
Caused by: java.lang.ClassNotFoundException: forestry.api.apiculture.EnumBeeChromosome
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 45 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.9.0-8-amd64
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 156640952 bytes (149 MB) / 678428672 bytes (647 MB) up to 723517440 bytes (690 MB)
	JVM Flags: 1 total; -Xmx775m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                            | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2            | minecraft.jar                                     | None                                     |
	| LCH   | mcp                               | 9.42              | minecraft.jar                                     | None                                     |
	| LCH   | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2768-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2838      | forge-1.12.2-14.23.5.2768-universal.jar           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | ic2                               | 2.8.159-ex112     | industrialcraft-2-2.8.159-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCH   | advanced_solar_panels             | 4.3.0             | Advanced+Solar+Panels-4.3.0.jar                   | None                                     |
	| LCH   | appliedenergistics2               | rv5-alpha-8       | appliedenergistics2-rv5-alpha-8.jar               | None                                     |
	| LCH   | battletowers                      | 1.6.4             | BattleTowers-1.12.2.jar                           | None                                     |
	| LCH   | bookshelf                         | 2.3.584           | Bookshelf-1.12.2-2.3.584.jar                      | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | carpentersblocks                  | 3.4.0-poc.6       | Carpenter's Blocks v3.4.0-poc.6 - MC 1.12.2.jar   | None                                     |
	| LCH   | codechickenlib                    | 3.2.0.345         | CodeChickenLib-1.12.2-3.2.0.345-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | redstoneflux                      | 2.1.0             | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cofhcore                          | 4.6.3             | CoFHCore-1.12.2-4.6.3.27-universal.jar            | None                                     |
	| LCH   | cofhworld                         | 1.3.1             | CoFHWorld-1.12.2-1.3.1.7-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | eplus                             | 5.0.176           | EnchantingPlus-1.12.2-5.0.176.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | endercore                         | 1.12.2-0.5.57     | EnderCore-1.12.2-0.5.57.jar                       | None                                     |
	| LCH   | thermalfoundation                 | 2.6.3             | ThermalFoundation-1.12.2-2.6.3.27-universal.jar   | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermalexpansion                  | 5.5.4             | ThermalExpansion-1.12.2-5.5.4.43-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | enderio                           | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderiointegrationtic             | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderiobase                       | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderioconduits                   | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderiointegrationforestry        | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderiointegrationticlate         | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderiomachines                   | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderiopowertools                 | 5.0.44            | EnderIO-1.12.2-5.0.44.jar                         | None                                     |
	| LCH   | enderstorage                      | 2.4.2.126         | EnderStorage-1.12.2-2.4.2.126-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | energyconverters                  | 1.3.0.15          | energyconverters_1.12.2-1.3.0.15.jar              | None                                     |
	| LCH   | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                        | None                                     |
	| LCH   | zerocore                          | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                       | None                                     |
	| LCH   | bigreactors                       | 1.12.2-0.4.5.67   | ExtremeReactors-1.12.2-0.4.5.67.jar               | None                                     |
	| LCH   | cfm                               | 6.3.0             | furniture-6.3.0-1.12.2.jar                        | None                                     |
	| LCH   | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.69.845.jar                   | None                                     |
	| LCH   | projecte                          | 1.12.2-PE1.4.1    | ProjectE-1.12.2-PE1.4.1.jar                       | None                                     |
	| LCE   | railcraft                         | 12.0.0-beta-1     | railcraft-12.0.0-beta-1.jar                       | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | solarflux                         | 4.32r             | SolarFluxReborn_1.12.2-4.32r.jar                  | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LC    | worldedit                         | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.57-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
	AE2 Version: alpha rv5-alpha-8 for Forge 14.23.0.2491
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by 3TUSK** [comment] 2019-06-17 23:36
Update your Railcraft to 12.0.0 release, you can get it here [https://minecraft.curseforge.com/projects/railcraft/files/2687757](https://minecraft.curseforge.com/projects/railcraft/files/2687757).

Duplicate of #1578, #1579, #1580, #1581 and #1587.

**Closed as completed** 2020-07-27 11:03 UTC
