### ISSUE TITLE
[1.12.2] multiblock tank have infinite storage

### ISSUE THREAD

**Issue by KP2048** [Railcraft/Railcraft#1649] opened 2019-01-13 22:38 UTC
**Description of the Bug**
my steel tank has infinite storage

**To Reproduce**
1. Build multiblock tank
2. try to fill the tank
3. the current fluid storage surpasses the capacity

**Expected behavior**
The tank would stop accepting fluid
**Screenshots & Video**
![2019-01-13_14 09 03](https://user-images.githubusercontent.com/39203202/51091468-cd85fe80-173f-11e9-83fe-dd6b5e43b490.png)
**Logs & Environment**
[https://gist.github.com/WitherTech/85f2f42eda978084a000829c2a01c9d3](url)

**Additional context**
I was trying to store liquid starlight from astral sorcery in a steel tank but it is storing it infinitely

**Comment by liach** [comment] 2019-01-13 22:45
Duplicate of #1567. Moving the issue there.

**Closed as completed by liach** 2019-01-13 22:45 UTC
Labels: duplicate
