### ISSUE TITLE
Crash on 1.12.2

### ISSUE THREAD

**Issue by Xorbah** [Railcraft/Railcraft#1580] opened 2018-12-25 14:22 UTC
**Environment**
 - 1.12.2 2796

---- Minecraft Crash Report ----

WARNING: coremods are present:
  HatedMobsLoadingPlugin (hatedmobs-1.3.0.jar)
  DynamicSurroundingsCore (DynamicSurroundings-core-1.12.2-3.5.4.0BETA.jar)
  LoadingPlugin (AdPother-1.12.2-0.9.6.0-build.0236.jar)
  CreativePatchingLoader (CreativeCore_v1.9.35_mc1.12.2 (2).jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.17_mc1.12.2 (1).jar)
  SSLoadingPlugin (SereneSeasons-1.12.2-1.2.15-universal.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  LoadingPlugin (BetterWithLib-1.12-1.5.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  LoadingPlugin (Quark-r1.5-135 (1).jar)
  CorePlugin (ForgeEndertech-1.12.2-4.4.5.0-build.0236.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-88.jar)
  AstralCore (astralsorcery-1.12.2-1.10.7.jar)
  LoadingPlugin (AdChimneys-1.12.2-3.3.15.0-build.0232.jar)
Contact their authors BEFORE contacting forge

// This doesn't make any sense!

Time: 12/25/18 8:18 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Railcraft (railcraft)
Caused by: java.lang.IllegalAccessError: no such constructor: mods.railcraft.common.items.ItemFilterBeeGenome.<init>()void/newInvokeSpecial

Didn't include the entire crash log because I believe the issue is here. It's looking for Forestry.

**Comment by walker-dev** [comment] 2018-12-25 14:36
dupe of #1578

**Closed as completed** 2018-12-25 17:17 UTC
