### ISSUE TITLE
Firestone ore not processable 1.10.2

### ISSUE THREAD

**Issue by Gunner76th** [Railcraft/Railcraft#1066] opened 2017-01-12 19:21 UTC
At present, I am not seeing any firestone generating in the nether. I do have RTG, Harvest Festival, and Geographicraft installed which all affect world gen as well. This has been confirmed by using gamemode 3, then flying around the nether using xray view to look at the lava floors. 

In addition to this, there is no registered way to process firestone ore into raw firestone, and in the latest release for 1.10.2 (Railcraft_1.10.2-10.0.1) there is no rock crusher listed. Previously this was the method for processing firestone ore into raw firestone.

**Comment by Gunner76th** [comment] 2017-01-12 19:26
In the config settings: 
      
        # spawns beneath the sea in spheres
        B:abyssal.geodes=true

        # spawns on lava sea floor in Nether
        B:firestone=true

those are both enabled, and we do have the Spheres, however for some reason we do not have firestone ore.

**Comment by Gunner76th** [comment] 2017-01-12 19:30
So I finally found naturally generating Firestone. I does appear to be spawning, albeit very rarely. 

This still however leaves the problem of not being able to process the ore into Raw Firestone.

**Comment by CovertJaguar** [comment] 2017-03-01 09:54
Duplicate of #1010

**Closed as completed by CovertJaguar** 2017-03-01 09:54 UTC
Labels: duplicate
