### ISSUE TITLE
Hide JEI recipes for disabled machines

### ISSUE THREAD

**Issue by WarlordWossman** [Railcraft/Railcraft#1705] opened 2019-02-10 10:39 UTC
**Is your feature request related to a problem? Please describe.**
I have used the railcraft config to disable some machines which I don't want to use for my modpack (which is a great option to have), the recipes for these machines do still show up in JEI even if the blocks are not getting loaded in. Metal rolling, coke oven, rock crusher and blast furnace.

**Describe the solution you'd like**
Check the config for disabled machines and hide the JEI tabs individually if they are disabled.

**Describe alternatives you've considered**
Instead of automatically hiding the JEI tabs based on blocks disabled in the config there could also be a specific config to disable the JEI tabs.

**Additional context**
![2019-02-10_11 25 38](https://user-images.githubusercontent.com/16925725/52532600-3e610c00-2d28-11e9-8d68-4c258b0117ec.png)
Recipes still showing even if the machines are turned off.

**Comment by liach** [comment] 2019-02-10 10:49
Duplicate of #1643.
https://github.com/Railcraft/Railcraft/commit/a7a282c2e88ef408d4af8999941afff055fb9f41#diff-7841a59195228cae33729fcb6f65172fR191

**Closed as completed by liach** 2019-02-10 10:49 UTC
Labels: duplicate
