### ISSUE TITLE
Liquid tanks does not work properly

### ISSUE THREAD

**Issue by Flammable4444** [Railcraft/Railcraft#1673] opened 2019-01-24 19:25 UTC
**Description of the Bug**
I can not properly build tanks from railcraft, it always have the wrong capacity (64,000), and blocks that used to build one of them have bugged names. While other features from this mod is working well, i have working coke over, and making steel and it's working fine, so the mod works, but something wrong with the tanks.

**To Reproduce**
1. Build tank with more capacity then 64,000
2. Use it
3. See the bug

**Expected behavior**
To have biggest capacity tank, i'v built steel and biggest tank, that supposed to store over 2mil, but it's still 64,000

**Screenshots & Video**
https://youtu.be/clR-03d_g1A

**Logs & Environment**
https://pastebin.com/EzkcK4kk

**Additional context**

Railcraft version:
railcraft-12.0.0-beta-4.jar
(
i tried beta1 and my game crashed, i tried beta 3 and have the same bug, this was downloaded here
https://minecraft.curseforge.com/projects/railcraft/files/2658671/download
)

Minecraft version: forge-1.12.2-14.23.5.2807

Other mods installed:
buildcraft-all-7.99.21
Computronics-1.12.1-1.6.5
industrialcraft-2-2.8.108-ex112
InventoryTweaks-1.64+dev.145
OpenComputers-MC1.12.2-1.7.3.146
treecapitator-mod-1.12

**Comment by liach** [comment] 2019-01-25 03:42
Duplicate of #1567. We are still devising a best fix for it, though we have multiple proposals ready.

**Closed as completed** 2019-01-25 03:44 UTC
Labels: duplicate
