### ISSUE TITLE
Competition of a recipe of a tin board and Tin Gear Bushing

### ISSUE THREAD

**Issue by karikusa** [Railcraft/Railcraft#1043] opened 2016-12-22 02:52 UTC
jei_1.10.2-3.13.6.392
Railcraft_1.10.2-10.0.1

It's the version which is so, but a recipe of a tin board and Tin Gear Bushing becomes same. Tin Gear Bushing can be produced at present, so I think it isn't so influential, but it'll be reported just in case.
When arrangement of a recipe of Tin Gear Bushing is changed to the one from which the center of the recipe of other gears was removed, material, several, 4, Tin Gear Bushing can be made while maintaining it, so how about changing it?
Or the hammer for exclusive use in business of IC2MOD to make each board, it's prepared and, by it seems whether would like.

English can't be used, so I'm using a translation site. I hope that it's transmitted neatly....

**Comment by karikusa** [comment] 2016-12-22 02:54
Oh, the version of Railcraft is Railcraft_1.10.2-10.0.1.

**Comment by liach** [comment] 2016-12-26 08:16
Dupe of #1013

**Closed as completed** 2016-12-26 11:52 UTC
