### ISSUE TITLE
Crash on startup with RC+LP+TE

### ISSUE THREAD

**Issue by SevenMass** [Railcraft/Railcraft#1852] opened 2019-06-23 12:01 UTC
**Description of the Bug**
The game crashes after launching, before the main menu appears. In MC v1.12.2

This bug appears when the following combination of mods (and their respective prerequisite mods) are all present:

RailCraft
Thermal Expansion (specifically this mod, the other Thermal mods work fine)
logistics pipes

Any 2 of the above will work, but all 3 combined cause the crash.

**To Reproduce**
Configure a modded Minecraft instance with:
Latest Forge for 1.12.2
Thermal Expansion and all its required dependency mods.
logistics pipes and its required dependency mod.
Railcraft

Then launch the game.
The crash will happen before the main menu appears.

**Logs & Environment**
https://gist.github.com/SevenMass/d325c42f00c2675310dfdba0f4e19c8d

**Comment by CovertJaguar** [comment] 2020-08-18 23:36
Duplicate of #1915

**Closed as completed by CovertJaguar** 2020-08-18 23:36 UTC
Labels: duplicate
