### ISSUE TITLE
Worldspike consumes full stack but accepts only 16 items

### ISSUE THREAD

**Issue by AstralJaeger** [Railcraft/Railcraft#1349] opened 2017-10-24 05:50 UTC
Hello,
on my survival server, I saw that when attempting to put a full stack of void powder in the Worldspike it consumes the full stack but will only accept 16 void powder and void the other 48.

**Comment by 3TUSK** [comment] 2017-10-24 06:31
If you are using shift while putting a full stack of void powder then this issue is duplicate of #1347

**Comment by AstralJaeger** [comment] 2017-10-24 09:01
Sorry wasn't able to decipher the title of #1347

**Comment by 3TUSK** [comment] 2017-10-24 14:42
Yeah that title ... should have been English for reference in future.

**Comment by liach** [comment] 2017-10-24 15:00
duplicate of #1347 then.

**Closed as completed by liach** 2017-10-24 15:00 UTC
Labels: duplicate
