### ISSUE TITLE
Opening Railcraft 12.0.0-b1 on latest forge cause crash

### ISSUE THREAD

**Issue by ccgfok** [Railcraft/Railcraft#1579] opened 2018-12-25 14:03 UTC
**Description of the Bug**
When I installed Forge 14.23.5.2796 [latest version for 1.12] and Railcraft 12.0.0-b1, it crashes after I opened MC.

**To Reproduce**
1. Install Forge 14.23.5.2796
2. Put Railcraft 12.0.0-b1 to the `mods` folder
3. Open MC.

**Additional context**
See full logs here: https://pastebin.com/hu1erQDy

**Comment by Marco4413** [comment] 2018-12-25 14:11
I had that crash too... To resolve it i've just installed Forestry and everything seems to work right!

**Comment by Xorbah** [comment] 2018-12-25 14:23
Not everyone wants to install Forestry. Lol

**Comment by walker-dev** [comment] 2018-12-25 14:36
dupe of #1578

**Closed as completed** 2018-12-25 18:21 UTC
Labels: duplicate
