### ISSUE TITLE
Crash on next page of recipes in JEI

### ISSUE THREAD

**Issue by Mxater** [Railcraft/Railcraft#1032] opened 2016-12-02 02:12 UTC
I see the recipes usage for cooper of industrial, on pass to page 2, this crash.

This is using in a server, if use this in SP, dont crash.

Iam use version Railcraft_1.10.2-10.0.1

https://gist.github.com/Mxater/af4693a93fa063f3d3a961c18348f62d

Sorry for my english...

**Comment by Ristellise** [comment] 2016-12-05 07:22
paging @mezz

**Comment by mezz** [comment] 2016-12-06 01:57
This looks like a normal rendering issue, it shouldn't be specific to JEI.

**Comment by liach** [comment] 2016-12-21 03:07
@Mxater Does this happen only with Railcraft on dedicated servers?

**Comment by Mxater** [comment] 2016-12-21 12:04
@liach, yes, only in dedicated servers.

El 21-12-2016 12:07 a. m., "liach" <notifications@github.com> escribió:

@Mxater <https://github.com/Mxater> Does this happen only with Railcraft on
dedicated servers?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/CovertJaguar/Railcraft/issues/1032#issuecomment-268423072>,
or mute the thread

**Comment by CovertJaguar** [comment] 2017-03-01 09:47
Duplicate of #1063

**Closed as completed by CovertJaguar** 2017-03-01 09:47 UTC
Labels: duplicate
