### ISSUE TITLE
Crash when placing trains with train placer.

### ISSUE THREAD

**Issue by Naxanria** [Railcraft/Railcraft#1711] opened 2019-02-11 16:46 UTC
**Description of the Bug**

Server crash when using the train placer.

**To Reproduce**

Train placer facing up with rail (total length of 4 long) on top, have electric locomotive with 1 cart as pattern, have the trains and carts inside the buffer.
Given a redstone signal will place the locomotive then crash.

**Logs & Environment**

 - Full log: 
https://gist.github.com/Naxanria/b376dd371f069c669df7fb50421a95f4
 - Crash report (If available): 
https://pastebin.com/XhPBkb1c

**Comment by liach** [comment] 2019-02-11 16:51
Duplicate of #1592. Will be fixed in beta 5.

**Closed as completed** 2019-02-11 16:51 UTC
