### ISSUE TITLE
 Iron tank accpeting more than max fluid

### ISSUE THREAD

**Issue by ramirez223** [Railcraft/Railcraft#1749] opened 2019-02-27 04:37 UTC
**Description of the Bug**
railcraft tank accepts more than its max of 64k mb of buildcraft oil

**To Reproduce**
1. Place 3x3x4 iron tank connect a ender tank to a opaque fluiduct to a tank valve
2. fill with cool buildcraft oil using a thermal dynamics opaque fluiduct
3. See that it goes past max of 64 buckets

**Expected behavior**
it goes to 64 buckets and stops
actual behavior:
goes past 64 buckets
**Screenshots & Video**
https://i.imgur.com/cwUKiNl.png

**Logs & Environment**
FTB ultimate reloaded version 1.2.0
https://paste.feed-the-beast.com/view/bdf2f99f

**Additional context**
updated to latest version of both buildcraft and railcraft manually with no change, even after breaking and replacing the tank in another spot

**Comment by liach** [comment] 2019-02-27 04:40
duplicate of the pinned issue #1567. wait for the next release.

**Closed as completed** 2019-02-27 04:40 UTC
