### ISSUE TITLE
[1.10.2] Forge 221 - Mod is asking forestry mod for bad commands. - Feature not added yet?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Railcraft/Railcraft#1074] opened 2017-02-02 22:29 UTC
https://gist.github.com/P3rf3ctXZer0/4f85461055b0cba5ed6d7107ef36ee15

**Comment by liach** [comment] 2017-02-02 23:54
Well, those items are simply not yet added back.

**Comment by P3rf3ctXZer0** [comment] 2017-02-04 09:36
Aw; it just said to report it.

**Comment by CovertJaguar** [comment] 2017-03-01 09:56
I think the Forestry syntax changed or something. I haven't looked at it.

It seems to be referencing a missing backpack? Maybe it got renamed.

**Comment by liach** [comment] 2017-03-01 17:36
Might be fixed by updating Forestry API and fixing compile errors.

**Comment by CovertJaguar** [comment] 2017-03-01 19:46
I doubt it, its an IMC error. Either something is wrong in how I'm defining my backpacks (highly possible) or something is wrong with the message itself.

**Comment by liach** [comment] 2017-04-09 07:47
Dupe of #981, closing

**Closed as completed by liach** 2017-04-09 07:47 UTC
Labels: duplicate, bug, low priority, mod compatibility
