### ISSUE TITLE
Furnance Minecart and Liquid Unloader issue

### ISSUE THREAD

**Issue by craft90** [Railcraft/Railcraft#846] opened 2016-06-26 21:32 UTC
I don't know if this is a bug or a feature but for some reason the vanilla Furnace Minecart exhibits strange behavior when it passes across a Locking Track on top of Liquid Unloader. For some reason the Locking Tracks locks the Furnace cart in place and it doesn't move until the fuel runs out or if it gets a manual redstone signal. I tried different modes both on the track and the loader but the same issue cropped up every time. I even tried to filter the Liquid Unloader but to no avail. I'm not sure what to do to solve the issue (I'm very new to Railcraft)

Just thought I should mention it if it was an issue (I'm running the latest RailCraft version for 1.7.10 in a custom modpack)

**Comment by craft90** [comment] 2016-06-26 22:06
So a few more details. In my system I had cresote oil. Even though the Unloader was set to Immediate (emit redstone signal if no liquid passes) the Locking Track still locked the furnace cart. A Furnace Minecart doesn't have liquid right? I tried it again in a different system, this time with water and the Locking track locked the Furnace Minecart in place at the Liquid Loader aswell. This happens both with the default setting and the Holding setting.

EDIT: Even if the Liquid Unloader is empty the Furnace Minecart gets locked in place!
EDIT 2: Only Locked Boarding track seems to work. As long as the Furnace cart isn't first.

**Comment by CovertJaguar** [comment] 2016-06-26 22:41
Odd... is it actually locked or just not moving? ie hit it with a crowbar and see if it moves.

**Comment by craft90** [comment] 2016-06-26 23:59
It's locked. Hitting it with a crowbar doesn't do anything. Not even jumping into a cart and try to manually move the train works. So either I have to give it a redstone signal or break the cart,

**Comment by craft90** [comment] 2016-06-30 18:48
Did some more poking around. Noticed an issue with the Item Unloader and Steve's Carts but then again Steve's Cart has their own cargo management, so maybe not important. But I digress. So I set up a easy track with Fluid Unloader/Loaders and Item Loaders/Unloaders and these Locking tracks. With only a Furnace cart running around the Locking Track, locked it above the Fluid Unloader (unless the Loader was full. Then it let it continue.) I tried all modes but with the same result. So maybe the Redstone signal isn't properly detected and sent?

I'll attach my set-up. (The Locking tracks are in Boarding mode because i noticed that the Holding ones was a little unreliable when using trains. Sometimes it boosted backwards.)
![2016-06-30_20 46 23](https://cloud.githubusercontent.com/assets/12762624/16500205/fbc0929a-3f03-11e6-8a7e-6d51a7834184.png)
EDIT: So the Liquid Unloader was set to Empty (hold until empty) which locked the Furnace cart in place. Switching modes fixed that issue. But then the Liquid Loader started locking the Furnace cart instead.

**Comment by craft90** [comment] 2016-06-30 18:55
Oddly enough the Furnace cart just stopped in this turn after the Items had been passed... That doesn't make much sense... It should keep pulling as long as it got fuel, shouldn't it? Hitting it with a crowbar makes it move like 10 pixels and then it stops.
![2016-06-30_20 53 04](https://cloud.githubusercontent.com/assets/12762624/16500483/084ff0c2-3f05-11e6-8beb-7eadd0865344.png)

**Comment by KnightMiner** [comment] 2016-06-30 21:36
Furnace carts stoping when going around corners is a vanilla bug

**Comment by craft90** [comment] 2016-06-30 22:39
But I haven't had any issues with that in any other set-up? Just this one. I got a really long creasot delivery system with a furnace cart and it works great. (as long as the furnace cart is last. Otherwise those Fluid Unloader + Locking Track stops it)

EDIT: And now the Liquid Loader is acting up instead... I have no idea what to do.
EDIT 2: Breaking and replacing the Liquid Loader fixed it... huh

**Comment by CovertJaguar** [comment] 2016-07-01 17:07
When using Trains (with locomotive/furnace cart) you will want to use the Locking Mode rather than Boarding or Holding, they don't need the boost.

Also furnace carts are really glitchy and weird, even in vanilla. I'd just make them actually, you know, cook things if I didn't think it would cause a riot.

**Comment by craft90** [comment] 2016-07-01 17:18
So just use the default setting? OK. Can do that. I'd use the Boarding Train setting though when using the furnace cart cos otherwise it would get stuck. (because when the first carts pass by the redstone signal remained so that the Furnace cart wouldn't get stuck.) Like I said I'm not that experienced in this.

BTW I did notice that the Item Unloader actually drains the fuel slot of a Locomotive unless it's filtered. I don't know what code you use for the Furnace cart but if it it's similar to that of the Locomotive then maybe the Unloaders/Loaders tries to drain stuff from non-existent slots? Keeping the cart stuck. Just a thought.

**Comment by CovertJaguar** [comment] 2016-07-02 01:12
It's possible, definitely seems like something isn't right. I make sure and test everything once I get it running on 1.9/1.10.

**Comment by CovertJaguar** [comment] 2016-10-06 00:05
Cannot reproduce in 1.10, closing until further info is forthcoming.

**Closed as completed by CovertJaguar** 2016-10-06 00:05 UTC
Labels: bug, needs verification, medium priority
