### ISSUE TITLE
steam boiler solid and fluid firebox game crash bug

### ISSUE THREAD

**Issue by dawnbraker2** [Railcraft/Railcraft#1881] opened 2019-09-04 06:15 UTC
Description of the Bug**
if you place liquid and solid fireboxes and complete the multi block it crashes minecraft and crashes when you try to rejoin the world (if you are looking to duplicate i suggest doing it in a fresh world as i have lost access to one of my worlds because of this bug)

**To Reproduce**
build a steam boiler multi block structure like you normally would but replace one of the solid/liquid fireboxes with the opposite type this intern crashes the game and ive been able to duplicate it several times

**Expected behavior**
i honestly expected the structure not to form but instead it crashed my game

**Screenshots & Video**
apologies i don't know what i could put here to help

**Logs & Environment**
https://github.com/dawnbraker2/crash-report
https://github.com/dawnbraker2/log

**Additional context**
i do have buildcraft and industrialcraft2 installed but i believe
i also would like to ask if there is a way to fix the world i was using when i found this bug** found way to disable boilers and fixed problem

**Comment by Ommina** [comment] 2019-09-04 06:44
For your final question only:

You can try setting **B:removeErroringTileEntities** to _true_ in forge.cfg and see if that gives you any joy in recovering your world.

**Comment by dawnbraker2** [comment] 2019-09-04 06:47
> For your final question only:
> 
> You can try setting **B:removeErroringTileEntities** to _true_ in forge.cfg and see if that gives you any joy in recovering your world.

Actually I found a way to disable boilers very shortly after and got my world back thank you though I'll keep that in mind in case I run into any similar problems in the future

**Comment by CovertJaguar** [comment] 2022-06-02 19:15
Duplicate of #1797

**Closed as completed by CovertJaguar** 2022-06-02 19:15 UTC
Labels: bug, medium priority, machines and structures
