### ISSUE TITLE
Oil Does not Work!

### ISSUE THREAD

**Issue by DiamondSwag** [Railcraft/Railcraft#1627] opened 2019-01-07 22:32 UTC
Hello,

Previously, BuildCraft had 1 oil, which was simply called "oil". Now, buildcraft segregates oil based on temperature to have a "cool", "warm", and "boiling" hot. Now that the oil is stateful, railcraft cannot load the oil into the trains. The oil simply does not go into the pump, since the filter cannot be set correctly. Thanks!

**Comment by CovertJaguar** [comment] 2019-01-08 00:05
Railcraft doesn't care about fluid type. I think this is actually a duplicate of #1549.

**Closed as completed by CovertJaguar** 2019-01-08 00:05 UTC
Labels: duplicate

**Comment by DiamondSwag** [comment] 2019-01-09 01:31
@CovertJaguar I am not quite sure. Normally, raiilcraft would work fine transporting large amounts of oil. Unfortunately, when setting the filter, it no longer works since buildcraft now has different 'types' of oil. This means the filter cannot be set, not allowing any oil to be pumped into trains. Therefore, I would consider this to still be a valid bug, and would appreciate if it would be treated as such.

**Comment by liach** [comment] 2019-01-09 01:34
Do different types of oil share the same bucket? I remember there are different types of buckets for different types of oils.

**Comment by DiamondSwag** [comment] 2019-01-09 19:46
No, but regular buildcraft oil now comes in three variants. Hot, searing, and cool. I guess the buildcraft integration hasn't been fixed for this change. Hence it should be reopened as a valid issue. I cannot fill a tank cart with oil.

**Comment by CovertJaguar** [comment] 2019-01-09 21:13
The point I was trying to make is that there _is no Buildcraft specific integration_ here.

The filter works on what is contained in the fluid container you put it in. I doesn't care if its water, oil, or flubber. If it fits in a bucket you can filter it.

It is already known that the Fluid Loaders are completely borked and not loading anything, not just oil.
