### ISSUE TITLE
Trackman entity crash with mod "Neat"

### ISSUE THREAD

**Issue by WesCook** [Railcraft/Railcraft#1173] opened 2017-04-25 20:29 UTC
This is related to the mod [Neat](https://minecraft.curseforge.com/projects/neat).  Viewing a Trackman villager will immediately crash the game.  These can be spawned in with the mob egg (and some luck) to test.

Crash log: https://pastebin.com/1fyYQRwS

For players: This can be temporarily worked around by adding "Villager" as an entry to the Neat blacklist.

**Comment by Generalcamo** [comment] 2017-04-26 03:17
@liach This one might concern you

**Comment by liach** [comment] 2017-04-26 04:15
Dupe of #1167. Medium priority because the game crashes.

**Closed as completed** 2017-04-26 04:15 UTC
Labels: duplicate, bug, needs verification, low priority, mod compatibility

**Comment by WesCook** [comment] 2017-04-26 11:03
Ah, so if I understand correctly the problem was that items being disabled would cause the villager to crash when the GUI was opened, and Neat simply exposed that information to the player sooner.  Is that right?

When removing Neat I found I couldn't actually open the trading GUI, but there may be additional checks in place there.

Thanks for looking into it in regardless.

**Comment by liach** [comment] 2017-04-26 13:56
Dunno what caused the other behavior, but I've fixed a crash of the same stacktrace.
