### ISSUE TITLE
Waiting for Server while exploring

### ISSUE THREAD

**Issue by Pentasis** [Railcraft/Railcraft#1642] opened 2019-01-12 11:50 UTC
1.12.2 beta-4

**Description of the Bug**
When generating new terrain I constantly get "Waiting for server" in waila/one probe and all entities "freeze" i.e. doors/chests do not open/close, mobs dont move etc. and chunks do not generate.
Closing the game hangs on "closing down server" and I need to kill the process manually.

**To Reproduce**
Don't know, it's not consistent
I do know that removing railcraft from the pack resolves the issue.

**Logs & Environment**
https://paste.ee/p/KbKlJ

I only have a client log since it does not generate an error.

**Comment by liach** [comment] 2019-01-12 13:41
Hmm, i have had this issue once as well when shutting down a sp testing world. Not sure if this is related to the logic issue i've fixed in #1641

**Comment by Pentasis** [comment] 2019-01-12 13:50
I'll add that since I removed railcraft from my pack, it has become very responsive. I had a lot of issues with world generation lag, stuttering (when moving), lighting updates, etc. I chalked them up to the pack being extensive (well, for my rig that is). I've been playing the pack for 2 weeks and had these problems from the start but I haven't had any of these problem after removing RC. Not sure if one relates to the other?

**Comment by liach** [comment] 2019-01-12 13:51
If those lag, stall, crash etc. happens with rc along, then it's railcraft's fault. wait for beta 5 and try again.

**Comment by CovertJaguar** [comment] 2019-01-12 22:51
Which logic issue? I'm not seeing any code that could cause this?

**Comment by liach** [comment] 2019-01-12 23:19
i mean that client desync caused by getting wrong interface on cart death

**Comment by liach** [comment] 2019-01-30 19:16
It might be some serious desync, We don't have enough proof for this unfortunately,

**Closed as completed by liach** 2019-01-30 19:16 UTC
Labels: need more info
