### ISSUE TITLE
Electric Locomotive with EU power super slow

### ISSUE THREAD

**Issue by chrizfilmz** [Railcraft/Railcraft#1648] opened 2019-01-13 15:53 UTC
Not much to write, electric locomotive moves super slow while having a power cart giving it power (atleast EU from CESU) no matter what speed i select in the locomotive GUI. Also the EU loader does not work on MFE cart (but it works on the others)

**Comment by WarlordWossman** [comment] 2019-01-13 17:58
I think you need a transformer upgrade in the EU loader to charge an MFE cart, at least that worked in beta 3, have not tested in beta 4 just yet.

But yeah the balance seems a bit weird and MFE carts are so heavy that they are super buggy I feel like (could be another reason tho). Wanted to wait a little before making an issue but since you report similar things I might as well comment on here.
Had issues with the MFE cart not linking right to the train and glitching inside of the train being stuck once I got them to link and also couldn't use the crowbar to rotate the MFE cart on rails by hand.

**Comment by CovertJaguar** [comment] 2019-01-13 20:30
MFE cart isn't rotation aware. Rotation is handled by vanilla code.

**Comment by CovertJaguar** [comment] 2019-01-13 20:31
Possibly related to #1577

**Comment by liach** [comment] 2019-01-13 22:51
Duplicate of #1624. See #1577 also. The MFE cart is definitely getting a throughout check.

**Closed as completed** 2019-01-13 22:55 UTC
Labels: duplicate
